### ISSUE TITLE
Streams für GUI/VIS kompatibel machen

### ISSUE THREAD

**Issue by nukleuz80** [bropat/ioBroker.eusec#153]
Hi bropat,

ist es dir möglich die Streams ob live oder vergangen für die grafischen Oberflächen gängig bzw. kompatibel zu machen?

Ich und auch andere brechen sich nen Zahn daran aus… 😂 echt frustrierend.

Bei mir selbst kommt Lovelace zum Einsatz. Dort habe ich auch schon mit dem DEV alle Möglichkeiten ausprobiert - doch es kommt kein Stream oder Ähnliches zustande… 

Oder bin ich einfach nur zu blöd? 🙈

Wenn ich mir die .m3u8 und die .ts files runterlade kann ich sie mit VLC öffnen und abspielen… 

Danke und Grüße

**Comment by bropat** [comment]
@nukleuz80 

Ist bereits auf meiner To-Do Liste, nur ist die mittlerweile ziemlich lang und meine Freizeit ziemlich kurz ;)

**Comment by nukleuz80** [comment]
Super! Dann hoffe ich, dass du die Zeit findest. 😇

**Comment by kksstefan** [comment]
Hallo,
ich habe es mit einem HTML Widget in VIS und einem .m3u8-HTML Player Skript zumindest schon mal hin bekommen
das, dass Video was im Datenpunk erscheint kurz abläuft. Vielleicht hat einer eine Idee wie man das Verbessern kann.


  <!DOCTYPE html>
    <html>
    <head>
    <meta charset=utf-8 />
    <title>Your title</title>
      
    
      <link href="https://unpkg.com/video.js/dist/video-js.css" rel="stylesheet">
      <script src="https://unpkg.com/video.js/dist/video.js"></script>
      <script src="https://unpkg.com/videojs-contrib-hls/dist/videojs-contrib-hls.js"></script>
       
    </head>
    <body>
      <video id="my_video_1" class="video-js vjs-fluid vjs-default-skin" controls preload="auto"
      data-setup='{}'>
        <source src="http://192.168.0.206:8082/eufy-security.0/T8020P10XXXXXXXX/live/T8222P00204XXXXXX.m3u8" type="application/x-mpegURL">
      </video>
      
    <script>
    var player = videojs('my_video_1');
    player.play();
    </script>
      
    </body>
    </html>

**Comment by guitardoc** [comment]
Wenn das käme, dann wäre das eine super Sache. Und noch dazu unbegrenzte Streamdauer. Dann könnte man von der VideoDoorbell über Vis das Bild dauerhaft streamen - oder gibts dazu eine andere Möglichkeit?
