### ISSUE TITLE
Passwort-Eingabe Feld verschwindet nach ersten Zeichen

### ISSUE THREAD

**Issue by nukleuz80** [bropat/ioBroker.euSec#163]
Hi bropat,

wenn man versucht ein Passwort im Adapter-Admin einzugeben ist das Feld nach Eingabe des ersten Zeichens umgehend verschwunden (nicht mehr sichtbar). Es kommt aber wieder, wenn man auf den Tabs hin und her springt.

Workaround: Passwort kopieren (Zwischenablage) und einfügen - Feld verschwindet trotzdem, ABER das Passwort wird dennoch übernommen!

Forum: https://forum.iobroker.net/topic/39276/neuer-adapter-eufy-security/204?_=1630319601405

![image](https://user-images.githubusercontent.com/43496030/131368459-81bcecf6-f723-437f-a681-dbcf1ebf1f85.png)

**Comment by bropat** [comment]
Hi @nukleuz80,

ich denke dies ist ein Problem des Admin-Adapters 5.x, da ab Version 5 eigentlich der Admin-Adapter die Einstellungen so gut wie selbst verwaltet (ich gebe ihm nur ein JSON-File als input).

Welche Admin Version hast du installiert?

**Comment by nukleuz80** [comment]
Ich bin auch auf der aktuellen 5er.

**Comment by bropat** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/1131

**Comment by cracyfloyd** [comment]
Same here today (14 Januar 2022)

**Comment by bropat** [comment]
Fixed with a workaround in version 0.8.2
