### ISSUE TITLE
[Question]: update auf 0.7.5 nice möglich?

### ISSUE THREAD

**Issue by bsaerdna** [bropat/ioBroker.eusec#205]
### Ask your question

das Update dauert sehr lange 

$ iobroker url https://github.com/bropat/ioBroker.eufy-security.git --host raspberrypi --debug
install bropat/ioBroker.eufy-security#a76933779d9c0a3fe9c935914502ee8e6f16729d
NPM version: 8.1.0npm install bropat/ioBroker.eufy-security#a76933779d9c0a3fe9c935914502ee8e6f16729d --prefix "/opt/iobroker" (System call)
up to date in 8m73 packages are looking for funding run `npm fund` for details
upload [5] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/words.js words.js application/javascript
upload [4] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/style.css style.css text/css
upload [3] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/jsonConfig.json jsonConfig.json application/json
upload [2] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/index_m.html index_m.html text/html
upload [1] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/eufy-security.png eufy-security.png image/png
upload [0] eufy-security.admin /opt/iobroker/node_modules/iobroker.eufy-security/admin/admin.d.ts admin.d.ts video/mp2t
Process exited with code 0

Am Ende tut er so als wäre er so weit aber ist kein Adapter zu sehen

**Comment by E-Stegemann** [comment]
Bei mir genau das gleiche.
![image](https://user-images.githubusercontent.com/71043988/146079827-5ef486db-5d4f-436b-9269-3dccd75584e5.png)

Scheinbar läuft die Installation nicht sauber durch.
Hat jemand eine Idee, wie man das korrigieren kann?
