### ISSUE TITLE
Last Pic Aktualisierung erst nach Neustart Adapter

### ISSUE THREAD

**Issue by Draexl** [bropat/ioBroker.eusec#208]
### Adapter version

0.7.5

### JS-Controller version

3.3.22

### Node version

v14.18.2

### Operating System type

Linux

### Operating system version

.

### Describe the bug

Kameratyp eufyCam 2C
Die Hinterlegten Bilder bei den Last Pic Datenpunkt "eufy-security.0.T80???????.cameras.????????.last_event_pic_url" werden erst nach Neustart des Adapter aktualisiert.
Verwendete Version 0.7.5 

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
@Draexl 

Bitte teste die gerade veröffentlichte Version (0.8.0) und gebe bitte Bescheid falls das Problem gelöst wurde.

**Comment by Mirko2211** [comment]
@bropat 

Moin, habe grad auf 0.8.0 aktualisiert. Leider keine Verbesserung bei mir. Wenn ich die Instanz neu starte ist das Bild wieder aktuell. Mir ist eben noch aufgefallen, das z.b. motion_detected auch nicht reagiert/aktualisiert.
Wenn ich Werte manuell ändere, wird es richtig umgesetzt. Z.b. light.
Zur Info, HomeKit Verbindung habe ich mal komplett deaktiviert.

**Comment by bropat** [comment]
@Mirko2211 

Ich benötige die Debug-Logs des Adapters um die Ursache zu finden. Kannst du bitte den Adapter im Debug-Modus versetzen, das Problem nachbilden und mir dann die Logs per Mail zusenden?

**Comment by Draexl** [comment]
> @Draexl 
> 
> 
> 
> Bitte teste die gerade veröffentlichte Version (0.8.0) und gebe bitte Bescheid falls das Problem gelöst wurde.

Wir Mirko schon geschrieben hat, leider keine Verbesserung (0.8.4)

**Comment by bropat** [comment]
@Draexl 

Ich benötige die Debug-Logs des Adapters um die Ursache zu finden. Kannst du bitte den Adapter im Debug-Modus versetzen, das Problem nachbilden und mir dann die Logs per Mail zusenden?

**Comment by Draexl** [comment]
Mache ich, wie kann ich dir das zusenden? Oder wie komme ich an die Mailadresse?

**Comment by Mirko2211** [comment]
Moin, gibts hier schon was neues? Waren die Logs aufschlussreich?

Liegt es vielleicht daran, das der Iobroker in einem Docker Container läuft?!

Gruß
Mirko
