### ISSUE TITLE
[Bug]: error: eufy-security.0 (1270) Response code not ok [{"code":26006,"msg":"Email address or password incorrect."}]

### ISSUE THREAD

**Issue by fountainedge** [bropat/ioBroker.euSec#216]
### Adapter version

0.7.5

### JS-Controller version

3.3.22

### Node version

14.18.3

### Operating System type

Linux

### Operating system version

11

### Describe the bug

I followed all the rules in the manual about configuration and authentication. I first tried with my existing account, then created a second Eufy account and I still receive the same message: 
error: eufy-security.0 (1270) Response code not ok [{"code":26006,"msg":"Email address or password incorrect."}]
error: eufy-security.0 (1270) Token error

Can anyone please help?

### To reproduce

1. Go to 'Setup of Eufy instance'
2. Click on 'username/password, type in correct login data'
3. Scroll down to 'log'
4. See error : eufy-security.0 (1270) Response code not ok [{"code":26006,"msg":"Email address or password incorrect."}]
error: eufy-security.0 (1270) Token error

**Comment by bropat** [comment]
Use latest version (0.8.2).
