### ISSUE TITLE
[Bug]: Solocam S40 connection issues

### ISSUE THREAD

**Issue by marcprenger** [bropat/ioBroker.eusec#217]
### Adapter version

0.7.5

### JS-Controller version

3.3.22

### Node version

14.18.2

### Operating System type

Linux

### Operating system version

Ubuntu server 5.4.0-96-generic

### Describe the bug

When trying to set the guard-mode of my 2x Solocam S40 (T8124) I'm getting a ERROR_CONNECT_TIMEOUT. 

![image](https://user-images.githubusercontent.com/27813142/151929504-9615e586-0d3f-47a8-b07f-c640a2d924ec.png)
![image](https://user-images.githubusercontent.com/27813142/151929685-b50fae3b-1f0f-4491-9c9e-bb9dfb5bef88.png)
![image](https://user-images.githubusercontent.com/27813142/151929712-86d96ae2-a4e1-4f32-957f-c0d2090b7c75.png)

When I restart the adapter it is working immediately.

![image](https://user-images.githubusercontent.com/27813142/151930000-3f1f9a19-fbf5-47dc-a209-cb741509601f.png)

### To reproduce

I'm currently not able to reproduce the issue. It appears after some time.

**Comment by Baenker** [comment]
Gilt auch für die E40. Derzeit mache ich täglich per cron ein Neustart vom Adapter. Über den Tag kann ich dann schalten…

**Comment by marcprenger** [comment]
Thanks Baenker, good workaround for the moment.

**Comment by bropat** [comment]
Please checkout the last version (0.8.0). Let me know if the problem persists.

**Comment by marcprenger** [comment]
I installed latest release (0.8.1) this morning and recognized no connection issues so far.
Let me wait another 1-2. If the issue has gone for sure, I will close this.

Many thanks for all the work you do, bropat!

**Comment by locito09** [comment]
have the same problem, no station found and no device found.
Device is a Eufy Doorbell

**Comment by marcprenger** [comment]
For me it seems to be fixed ...
