### ISSUE TITLE
[Bug]: MQTT Error during adapter start

### ISSUE THREAD

**Issue by zbigniewbednarek** [bropat/ioBroker.euSec#221]
### Adapter version

0.8.1

### JS-Controller version

3.3.22

### Node version

12.22.7

### Operating System type

Other

### Operating system version

Linux raspberrypi 5.10.63-v7l+

### Describe the bug

Hello,
After installing latest version of the adapter 0.8.1 I see following error message in the logs after each adapter restart.
eufy-security.0 6372	2022-02-06 10:06:18.092	info	MQTT connection closed
eufy-security.0 6372	2022-02-06 10:06:18.083	error	MQTT Error [{"code":5}]

Is it normal ? 
Thank you!

### To reproduce

1. Stop / Start or restart adapter
2. Go to Logs
3. Search for following errors:
eufy-security.0 6372	2022-02-06 10:06:18.092	info	MQTT connection closed
eufy-security.0 6372	2022-02-06 10:06:18.083	error	MQTT Error [{"code":5}]

### Screenshots & Logfiles

eufy-security.0 6372	2022-02-06 10:06:18.092	info	MQTT connection closed
eufy-security.0 6372	2022-02-06 10:06:18.083	error	MQTT Error [{"code":5}]

**Comment by bropat** [comment]
Fixed in version 0.8.2
