### ISSUE TITLE
[Question]: Update from 0.8.1 after change of name

### ISSUE THREAD

**Issue by harryslapalot** [bropat/ioBroker.eusec#227]
### Ask your question

I might look like an idiot by asking this but can anyone point me in the right direction how to update from 0.8.1 to 0.8.3 after the name was changed? When I install the adapter by URL a new adapter is created with the new name. How can I just update the old adapter that works with my installed instance? I would prefer not to change all references to the adapter in my scripts.
Is there any way to do this at all or do I have to start from scratch just because the name was changed?
Thanks for your help!

**Comment by SSpecken** [comment]
Just open the console of your ioBroker installation and run:

`iobroker url https://github.com/bropat/ioBroker.euSec eusec `

**Comment by harryslapalot** [comment]
Thanks for your answer. Unfortunately I get the same result. A new adapter is installed (I now have eufy-security with one instance and the new eusec adapter. How can I keep the objects created by the instance of eufy-security?

**Comment by beandi** [comment]
I have the same problem, eufy-security (0.7.4) ist installed, euSec (0.8.2) it listed as a new adapter.
is an update with the name change even possible?

**Comment by Sascha-U** [comment]
I have the same issue. Installing the new renamed adapter shows a separate entry. The old adapter (eufy sicherheit )is not updated. Is there any way to rename the adapter on iobroker to fit the new name or how should I proceed. I would like to avoid recreating everything that uses the old name.

**Comment by bropat** [comment]
It was renamed for trademark infringement.

Unfortunately, you can not rename anything. What you can do of course is not to build directly on the objects of the adapter for scripts, but on so-called aliases that abstract the whole thing. see for example:

https://github.com/sbormann/ioBroker.alias-manager
