### ISSUE TITLE
[Bug]: Fehlermeldung beim Start mit V.0.84

### ISSUE THREAD

**Issue by Baenker** [bropat/ioBroker.eusec#229]
### Adapter version

0.84

### JS-Controller version

nicht relevant

### Node version

nicht relevant

### Operating System type

Linux

### Operating system version

nicht relevant

### Describe the bug

beim Adapterstart bekomme ich folgende Meldung:

`

2022-02-10 20:50:18.915 | error | Status return code not 200 [{"status":423,"statusText":"Locked"}]
-- | -- | --

`

### To reproduce

Adapter starten

### Additional context

Es läuft alles. Er sagt zwar auch keine Kameras gefunden. Was halt nur so halb stimmt. Der User den ich verwende hat keine eigenen Kameras sondern nur freigebende von mir. Hintergrund warum ich das so mache ist das ich in der eufy-App somit sehe das ich z. B. eine Kamera mit dem User "ioBroker" geschaltet habe und nicht ich oder meine Frau manuell geschaltet haben...

**Comment by scottmil** [comment]
I have a similar issue after installing version 8.4.  Attached is my log file and eusec.0 instance screenshot
[scottmil-ioBroker.log](https://github.com/bropat/ioBroker.eusec/files/8044791/scottmil-ioBroker.log)
<img width="962" alt="scottmil-eusec 0" src="https://user-images.githubusercontent.com/10510570/153508704-a032220c-38ad-4c61-85fe-37e891ead04b.png">

.

**Comment by tintim** [comment]
I appear to have two copies of Eufy Security following the latest updates, I guess I need to uninstall my original instance and reconfigure?

![image](https://user-images.githubusercontent.com/10616165/153641748-16629055-79db-4daa-ae97-3ceb2306a704.png)

**Comment by scottmil** [comment]
tintim: I deleted my original instance and older adapter and installed/reconfigured the newer euSed adapter and instance. I had few references to the older version in my scripts, so this was not a big headache.  If you have lots of references in your scripts, I recall bropat suggested using the Alias-Manager adapter to create aliases for your script references.
<img width="337" alt="Screen Shot 2022-02-11 at 12 18 38 PM" src="https://user-images.githubusercontent.com/10510570/153665029-87bb06ad-1328-4892-83fb-88fcac474840.png">

**Comment by tintim** [comment]
Thanks Scottmill cleaned up the old instance and installed the new version, a simple find/replace on my yaml scripts sorted any previous weblinks.
