### ISSUE TITLE
adapter restart results in having eufy-security object tree

### ISSUE THREAD

**Issue by marcprenger** [bropat/ioBroker.eusec#234]
### Adapter version

0.8.5

### JS-Controller version

3.3.22

### Node version

14.18.2

### Operating System type

Linux

### Operating system version

Ubuntu server 5.4.0-96-generic

### Describe the bug

After restarting the adapter some devices are written to old object tree "eufy-security." instead of "eusec."

![image](https://user-images.githubusercontent.com/27813142/155283823-c20ef322-e6ec-45f3-802d-faa574fe0228.png)

Let me know what you need to troubleshoot

### To reproduce

Restart adapter

**Comment by bropat** [comment]
That is not possible. The renamed adapter writes in the new tree and the old one in the old one.
Furthermore, you should uninstall the old adapter and delete the corresponding tree manually.
