### ISSUE TITLE
[Bug]: Camera stream for only 30 sec

### ISSUE THREAD

**Issue by rfnovo** [bropat/ioBroker.eusec#236]
### Adapter version

0.8.4

### JS-Controller version

v5.3.1

### Node version

V14.19

### Operating System type

Docker

### Operating system version

Ubuntu 20.04

### Describe the bug

When toggling the "start_stream", the livestream correctly received the m3u8 url but it will only stream for 29 sec before stopping and the following is logged: Stopping the station stream for the device T8200N10204911EB, because we have reached the configured maximum stream timeout (30 seconds)

But Live stream setting for the adapter instance is set to 180 sec
![timeout](https://user-images.githubusercontent.com/11941836/155885518-6a0e891e-056f-49c8-aaeb-44c1f95d82cc.png)

### To reproduce

As described in the bug

**Comment by bropat** [comment]
Will be fixed in the next version
