### ISSUE TITLE
[Bug]: Error messages in log when changing object "guard_mode"

### ISSUE THREAD

**Issue by harryslapalot** [bropat/ioBroker.eusec#238]
### Adapter version

0.8.4

### JS-Controller version

4.0.15

### Node version

14.17.0

### Operating System type

Docker

### Operating system version

20.10.3-1239

### Describe the bug

When I change the guard_mode of my Homebase or cameras via script to "1", "0", "3" or "63" I get the following error messages in the log. Sometimes the instance turns yellow and stops working. I set the guard mode of the homebase and 4 cameras. I have already tried to include a delay of 2 seconds between changing the individual objects.

### To reproduce

Set guard_mode to "0", "1", "3" or "63" and check log.

### Screenshots & Logfiles

<html>
<body>

eusec.0 | 2022-03-09 16:41:58.020 | info | No devices found.
-- | -- | -- | --
eusec.0 | 2022-03-09 16:41:58.019 | error | Response code not ok [{"code":"250999","msg":"The request is too fast. Please stop and have a rest"}]
eusec.0 | 2022-03-09 16:41:57.797 | info | No devices found.
eusec.0 | 2022-03-09 16:41:57.796 | error | Response code not ok [{"code":"250999","msg":"The request is too fast. Please stop and have a rest"}]
eusec.0 | 2022-03-09 16:41:57.755 | info | No stations found.
eusec.0 | 2022-03-09 16:41:57.754 | error | Status return code not 200 [{"status":423,"statusText":"Locked"}]
eusec.0 | 2022-03-09 16:41:57.709 | info | No houses found.
eusec.0 | 2022-03-09 16:41:57.709 | error | Status return code not 200 [{"status":423,"statusText":"Locked"}]
eusec.0 | 2022-03-09 16:41:56.431 | info | No stations found.
eusec.0 | 2022-03-09 16:41:56.431 | error | Response code not ok [{"code":"250999","msg":"The request is too fast. Please stop and have a rest"}]
eusec.0 | 2022-03-09 16:41:55.194 | info | No stations found.
eusec.0 | 2022-03-09 16:41:55.193 | error | Response code not ok [{"code":"250999","msg":"The request is too fast. Please stop and have a rest"}]
eusec.0 | 2022-03-09 16:41:49.643 | info | Alarm mode for station T8010P23195003DF changed to: HOME

</body>
</html>

**Comment by harryslapalot** [comment]
Does anyone have an idea what these errors mean at all? I have not even the slightest idea what the problem is here?

**Comment by bropat** [comment]
The above error indicates a problem with authentication. In the next version, some race conditions in the authentication will be fixed.

**Comment by Baenker** [comment]
habe das gleiche Problem. Ich schalte 4 Kamera wenn ich Abwesend bin.
