### ISSUE TITLE
Problem bei Update von 0.8.4 auf 0.9.1

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#251]
### Adapter version

0.8.4 

### JS-Controller version

 4.0.23

### Node version

14.19.1

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Update schlägt fehl

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

$ iobroker upgrade eusec@0.9.1

Update eusec from @0.8.4 to @0.9.1

NPM version: 6.14.16

Installing iobroker.eusec@0.9.1... (System call)

upload [14] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/eusec.png eusec.png image/png

upload [13] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [12] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [11] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/es/translations.json i18n/es/translations.json application/json

upload [10] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [9] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/it/translations.json i18n/it/translations.json application/json

upload [8] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [7] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/pl/translations.json i18n/pl/translations.json application/json

upload [6] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [5] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/ru/translations.json i18n/ru/translations.json application/json

upload [4] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json

upload [3] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/index_m.html index_m.html text/html

upload [2] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/jsonConfig.json jsonConfig.json application/json

upload [1] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/style.css style.css text/css

upload [0] eusec.admin /opt/iobroker/node_modules/iobroker.eusec/admin/words.js words.js application/javascript

Process exited with code 0

### Additional context

Hallo Bropat, beim Update auf 0.9.1 bleibt die Info und die Adapter Info auf Aktualisierung stehen. 

Das Update läuft durch, aber es ändert sich nichts. 
Die Info bleibt das es eine neue Version gibt wie auch unter Adapter wird immer noch angezeigt das es eine neuere Version gibt. 

**Das Update läuft fehlerfrei durch:** aber die alte Version wird nicht ersetzt.

**Comment by SSpecken** [comment]
Same here: Upgrade von 0.8.5 auf 0.9.1:

- Plattform: linux
- Node.js: v14.19.1
- NPM: 6.14.16

**Comment by bropat** [comment]
@sansonifabio 

Hab vergessen auf npm zu veröffentlichen... Ist nun geschehen.

@SSpecken 

Forgot to publish on npm.... It is done now.

**Comment by sansonifabio** [comment]
Guten morgen @bropat,

vielen Dank für deine Mühen. 
Hat jetzt geklappt. Da ist mir jetzt aufgefallen das die Überschrift in der Eusec Adapter kachel fehlt
![eusec](https://user-images.githubusercontent.com/88761140/166864694-19f68e24-e248-4705-9213-828fa4578991.jpg)
.

Herzliche Grüße
Fabio

**Comment by sansonifabio** [comment]
Hallo @bropat,

hat sich erledigt nach Neustart von ioBroker ist die Überschrift wieder da.
