### ISSUE TITLE
[Question]: Live Stream

### ISSUE THREAD

**Issue by Longbowbln** [bropat/ioBroker.eusec#254]
### Ask your question

Hallo, 

so habe Ihn installiert bekommen, nur wieso steht bei Live Stream kein Datenpunkt, aber (Null). 
Wie kann ich die in einem VIS / Widget einbinden... Ich habe dickes Fragezeichen.

**Comment by zoulhh** [comment]
Du musst den Live Stream über start_stream (Button) starten. Dann steht da auch was. Wie ich den Livestream allerdings in vis einbinde, wüsste ich auch gern.

**Comment by zoulhh** [comment]
Ich auch.

**Comment by MojitoJoe1813** [comment]
Und ich erst.

**Comment by zoulhh** [comment]
Ich habs jetzt gelöscht. Bei mir hat praktisch nichts funktioniert. Manchmal gab es Event-Bilder, aber die verschwanden auch schnell wieder. Bin einfach durch das Konzept nicht durchgestiegen.
