### ISSUE TITLE
[Feature request]: Disable Downloads

### ISSUE THREAD

**Issue by MrDrache333** [bropat/ioBroker.eusec#255]
### Describe the solution you'd like

I would like to have a Checkbox to completely disable downloads for Images and Videos.

**Comment by Baenker** [comment]
Für Videos gibt es das ja schon. Für Fotos wäre es für mich auch sinnvoll, da es mit meinen Kamera sowieso nicht funktioniert und es im log beim download immer zu Fehler kommt.
