### ISSUE TITLE
[Question]: How do I update the adapter?

### ISSUE THREAD

**Issue by Pongard** [bropat/ioBroker.eusec#256]
### Ask your question

This might be straight forward for some, but I can't figure out how to update the adapter. 

- iobroker update
- iobroker upgrade

doesn't work. 

- npm install

would just install but not update, right?

**Comment by SSpecken** [comment]
Hi pongard,

just use the update function in the web gui under the adapter section and the eusec adapter. 

Or if you like it old school in the terminal:

iobroker upgrade eusec@0.9.1

**Comment by Pongard** [comment]
After executing the statement I have two adapters.
Did I happen to just have a very old outdated adapter?
I guess I have to uninstall it and update my scripts?

![image](https://user-images.githubusercontent.com/5831024/168463999-0f9655f5-b985-40f4-8fcb-9228cb580789.png)

**Comment by SSpecken** [comment]
> After executing the statement I have two adapters.
> Did I happen to just have a very old outdated adapter?
> I guess I have to uninstall it and update my scripts?

I hope I’m right: Because of name rights/copyright issues bropat had to rename his project to eusec. But this lead to a new adapter and you‘ll have to delete the old adapter and update your script‘s.

**Comment by bropat** [comment]
What @SSpecken says is right. Furthermore, you should have a message in the info page (the message is only visible to those who still have the old adapter installed) that says exactly what @SSpecken says.

**Comment by Pongard** [comment]
The message is not there, but at least I know now what's the issue and how to solve it. Thanks guys!

**Comment by bropat** [comment]
Maybe it is already expired...
