### ISSUE TITLE
[Feature request]: Quick response (only doorbells) for the Adapter

### ISSUE THREAD

**Issue by robudus** [bropat/ioBroker.eusec#259]
### Describe the solution you'd like

Hi, thanks for the great plugin. Its possible to ads quick response (only doorbells) in the adapter. The [eufy-security-client](https://github.com/bropat/eufy-security-client) library offers the feature. It would be awesome to send quick response in iobroker if the bell rings. Thank you very much. You can send six quick responses to the doorbell. And someone who rings can get them as voice Message. Please integrate this in this plugin.

Thanks

Regards 
ROBudus

**Comment by bropat** [comment]
@robudus 

I can also implement this functionality here. But I need access to the device so that I can test everything.
Can you share the device with me?

**Comment by robudus** [comment]
Hi,
what do you need from the device? I use ist since 3 Years without problems
every day in my home.

ROBudus

Am So., 6. Nov. 2022 um 10:30 Uhr schrieb bropat ***@***.***>:

**Comment by bropat** [comment]
I need access to test the correct implementation of this functionality. Otherwise, I cannot guarantee that it will work.
e.g. the Cloud API only provide an answer about the available voices if the device supports them.
I myself do not own a device with this functionality.

**Comment by bropat** [comment]
Anyone who wants to share the device so I can implement and test this feature here?
