### ISSUE TITLE
[Bug]: unable to Switch on/off "enable" and "motion_detection"

### ISSUE THREAD

**Issue by hohmannc85** [bropat/ioBroker.eusec#260]
### Adapter version

0.9.1

### JS-Controller version

4.0.23

### Node version

16.15.1

### Operating System type

Linux

### Operating system version

RaspOS

### Describe the bug

Hello, in the my camera "Floodlight" enable and motion_detection says "(null)"
if I change the state nothing happens.
Same procedure works on my indoor Cameras!
Is Floodlight not supported?

### To reproduce

choose Floodlight Cam

**Comment by bropat** [comment]
@hohmannc85 

There are several different Floodlight devices and different firmware versions with different behaviour...
With the information provided and without debug logs, I can't help you.

**Comment by hohmannc85** [comment]
![42D298DA-0123-42EB-9A6A-0575C75A35E6](https://user-images.githubusercontent.com/65295025/177047794-8f9a9009-873e-46fe-b0d0-0e94d793c566.png)

**Comment by bropat** [comment]
@hohmannc85 

Try version `0.9.5` and let me know.
