### ISSUE TITLE
[Bug]: Error Downloading Thumbnail Image After Motion Detection

### ISSUE THREAD

**Issue by scottmil** [bropat/ioBroker.eusec#265]
### Adapter version

0.9.1

### JS-Controller version

4.0.23

### Node version

17.9.0

### Operating System type

Other

### Operating system version

Raspberry Pi Buster

### Describe the bug

The adapter log warns "Could not download" after multiple attempts to retrieve a thumbnail JPG image after motion is detected.

### To reproduce

1. Eufy Wireless Doorbell detects motion.
2. Adapter log warns "Could not download" after 5 attempts to retrieve the motion thumbnail image.
3. Manually clicking on the still image URLs in the adapter log after a few minutes USUALLY results in a successful thumbnail image retrieval. Examples from attached log: https://security-app.eufylife.com/v1/s/g/a7hvPvNJu, https://security-app.eufylife.com/v1/s/g/5r7_8ZSkL
4. EXCEPTION: Manually clicking on the URL for motion detected at 2022-07-08 19:08.47 after a few minutes following detection resulted in the attached XML error message.  However, a subsequent motion detection 2 hours later (21:28) resulted in retrieval of a thumbnail image (attached) at an identical URL as the 19:08:47 thumbnail URL.   Possible clues: The XML error message Key mentions the date 2022-07-09 when the motion detection actually occurred on 2022-07-08.  The thumbnail retrieved for the motion detected at at 21:28 on 2022-07-08 has the correct timestamp.

### Screenshots & Logfiles

<img width="1119" alt="ioBroker log-Could not download" src="https://user-images.githubusercontent.com/10510570/178128507-9b4aad2f-c772-4ab0-8d6f-16fb5ce09987.png">

![DatGuRtjqN2ba7Yy](https://user-images.githubusercontent.com/10510570/178128514-04c47457-e6bc-4779-a5fc-6a2096b0135d.jpg)

![SLzJuuMQTOv4ZL9b](https://user-images.githubusercontent.com/10510570/178128517-153674bf-7926-495e-ad2f-3ca83303b544.jpg)

<img width="765" alt="20220708 19-09-38-172 Error Downloading" src="https://user-images.githubusercontent.com/10510570/178128521-34a8954a-f289-4c08-8948-b8132aa70c8f.png">

![RdaGuLzRbNNIpUxl](https://user-images.githubusercontent.com/10510570/178128526-6ac46184-0f55-41be-992a-86ffeff6fc02.jpg)

**Comment by cratoo** [comment]
I basically have the same issue, but I'm not sure if this is a problem of the adapter. Actually I think that the cloud is informed about a motion detection and pregenerates a url for this picture and is waiting for the upload of the camera. Until this upload is done, the image download will result in an 404 error message. But this is just wild guessing.
@bropat I remember that we talked about the option of taking the picture out of the recording in the second after the motion detection. Do you think this is possible or may I even remember it wrong?

Additionally I just tried to reduce image/video quality. Let's see if this helps.

What also came to my mind: in the beginning of using the camera I enabled rtsp streaming to my nas, which still works but apparently the configuration for this vanished from the app. I could imagine that streaming an event to the nas and additionally creating the snapshot could result in this delay. But as the configuration vanished I could only disable it in the nas, without knowing if this has an effect on the camera.

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
