### ISSUE TITLE
[Feature request]: Homebase Alarm

### ISSUE THREAD

**Issue by MarcCCAA** [bropat/ioBroker.eusec#271]
### Describe the solution you'd like

Hi,
ich würde mich gerne von Telegram anrufen lassen wenn ein Alarm ausgelöst wird.
Hab dazu allerdings keinen Datenpunkt im Adapter gefunden und habe ihn auch hoffentlich nicht übersehen.
Der Alarm kommt ja auch als Push über die App, ist es da möglich den aus zu lesen und im Adapter zu nutzen?
Thx Marc

**Comment by denjo82** [comment]
Läuft der Adapter auch mir der eufy Security Video Doorbell???
