### ISSUE TITLE
[Feature request]: Trigger Alarm of Camera individually

### ISSUE THREAD

**Issue by lettersfromfelix** [bropat/ioBroker.eusec#273]
### Describe the solution you'd like

Hi,
First of all thanks for your work!
One question: Would it be possible to integrate a trigger for the alarm sound of cameras w/o using the homebase as in [#76]? I for myself (and probably others as well) only have cameras without having any homebase at all, and directly using them e.g. with HomeKit. Triggering the alarm would make it very useful for a custom alarm.
Thanks in advance and cheers!

**Comment by bropat** [comment]
This functionality is already included (`trigger_alarm_sound` / `reset_alarm_sound`).
