### ISSUE TITLE
[Question]: No battery values for eufy2 cameras

### ISSUE THREAD

**Issue by n0valis** [bropat/ioBroker.eusec#275]
### Ask your question

I have successfully connected the adapter to my two eufy2 cams. With the previous iobroker eufy adapter I could read my battery values. Yours seems to have difficulties. Values are null. As are speaker_volume, wifi_signal_level and some others. Not all though. Any idea?

**Comment by bropat** [comment]
Hi,
if by previous adapter you mean ioBroker.eufy-security, then it's still mine ;) It has just been renamed.
Without debug logs I can't help you.

**Comment by n0valis** [comment]
Please help me, what kind of debug logs?

**Comment by n0valis** [comment]
I am not sure what happend :-o  
I didn't do anything but the missing value suddenly appeared.

**Comment by bropat** [comment]
For next time, [here](https://github.com/bropat/ioBroker.eufy-security/wiki/Howto-enable-debug) is the wiki entry to enable debug mode.
