### ISSUE TITLE
[Question]: How to choose house?

### ISSUE THREAD

**Issue by api2001** [bropat/ioBroker.eusec#282]
### Ask your question

Hi,

I am not quite sure what is the problem here - I suppose it is just me and my non-understanding ;-)
When I integrate the adapter, connection is established, all green, but the log shows:
No devices found.
No stations found.

When switching to debug logging there is also a line:
Houses - house name: xxx***'s Home

The adapter seems to choose a house. However in the app we use a different house with a different name "Guesthouse", not "xxx***'s Home".
Might this be a reason why no stations nor devices can be found? Because stations/devices are queried from the wrong house?
Also when I add a new Eufy user "abcdef@gmail.com" and share our "Guesthouse" with him, the adapter's log shows:
Houses - house name: abc***'s Home.

Thanks for any help!
APi

**Comment by royakaacky** [comment]
I have the same problem. the logs shows: 

No devices found.
No stations found.

The instance is green. But i dont understand why. My account has two factor authentication enabled. But the instance is green without entering two factor code. In the logs there was no request for the verification code.

Maybe this is the problem? 

In the documentation https://bropat.github.io/ioBroker.eusec/#/configuration there was recommended to use a separete account.  I also tried to invite a separate account and login this separete account in the adapter. But there was the same result.

**Comment by bropat** [comment]
@api2001 @royakaacky 

The adapter does not select a specific house, but it corresponds to the "All devices" view of the Eufy app.

The adapter uses the country setting under ioBroker to find the devices. If you have registered the Eufy devices under a different country than you have set in ioBroker, the adapter will not find your devices.
