### ISSUE TITLE
No Devices found

### ISSUE THREAD

**Issue by royakaacky** [bropat/ioBroker.eusec#285]
### Adapter version

0.9.4

### JS-Controller version

4.0.23

### Node version

16.17.0

### Operating System type

Linux

### Operating system version

 Raspbian GNU/Linux 11 (bullseye)

### Describe the bug

My Instance found no devices
the logs shows:

No devices found.
No stations found.

The instance is green. But i dont understand why. My account has two factor authentication enabled. But the instance is green without entering two factor code. In the logs there was no request for the verification code.

Maybe this is the problem?

In the documentation https://bropat.github.io/ioBroker.eusec/#/configuration there was recommended to use a separete account. I also tried to invite a separate account and login this separete account in the adapter. But there was the same result.

### To reproduce

I installed the adapter and then logged in. The instance is connected. But one devices are found

### Screenshots & Logfiles

![image](https://user-images.githubusercontent.com/35071084/191984063-8ea41661-3940-4492-b08f-20fe3e0276d7.png)
![image](https://user-images.githubusercontent.com/35071084/191984105-40ac0d67-0efe-461b-98e1-955a257b35f9.png)

**Comment by edgarloxton** [comment]
I have the same problem. I don't have 2 factor authentication. Also tried it with two eufy accounts - one with the devices originally added to and one with them shared. 

Adapter version
0.9.4

JS-Controller version
4.0.23

Node version
16.17.0

Operating System type
Linux

Operating system version
Ubuntu 

Describe the bug
My Instance found no devices and no stations. 
the logs shows:

No devices found.
No stations found.

**Comment by bropat** [comment]
@royakaacky @edgarloxton 

The adapter uses the country setting under ioBroker to find the devices. If you have registered the Eufy devices under a different country than you have set in ioBroker, the adapter will not find your devices.
