### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by mom4y** [bropat/ioBroker.eusec#288]
### Ask your question

Thnks for this helpful adapter - I switched from Homebase 2 to Homebase 3.
Is there a chance to implement the Homebase 3 (S380) with the eufyCam3 (S330) into the adapter as supported devices ?  
With v0.9.4 Hombase3 (S380) is displayed in objects but log shows "All address lookup tentatives failed." EufyCam3 (S330) isn't displayed  in objects - Parallel installed Homebase 2 is working well with eufyCam2C.

**Comment by bropat** [comment]
@mom4y 

In the next release it will be supported.
