### ISSUE TITLE
[Bug]: Error readValue param 1271 [{"code":"ERR_INVALID_ARG_TYPE"},1271,{"account_id":"xxxxxx","snooze_time":0}]

### ISSUE THREAD

**Issue by Baenker** [bropat/ioBroker.eusec#293]
### Adapter version

0.9.5 und 0.9.6

### JS-Controller version

4.0.23

### Node version

14.x

### Operating System type

Linux

### Operating system version

nicht relevant

### Describe the bug

Wenn ich bei einer Kamera den Modus auf Abwesend stelle oder deaktiviere bekomme ich den o. g. Fehler ins log.

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
@Baenker 

Kannst du bitte den Adapter kurz im Debug-Modus versetzten, das Problem nachbilden und mir dann per Mail (patrick.broetto@gmail.com) zusenden?

Danke!

**Comment by Baenker** [comment]
Habe Dir das log zugeschickt.

**Comment by rumpeltec** [comment]
Hallo zusammen,

ich habe genau dieselbe Fehlermeldung seit Version 0.9.5, jedoch ohne irgendeine Aktion vorher ausgeführt zu haben.
Tritt völlig unvermittelt, mehrmals am Tag auf. Dann aber u.U. im Minutentakt für eine Stunde. Dann ist wieder Ruhe.
