### ISSUE TITLE
[Question]: Custom voice output of camera

### ISSUE THREAD

**Issue by foxriver76** [bropat/ioBroker.eusec#296]
### Ask your question

Hey, thanks for your great work with this adapter. 

Is it possible to control the voice output of a camera by e.g. providing an `mp3` file? 

I guess it is what is implemented as `talkback` via https://github.com/bropat/eufy-security-client/commit/9aa3a7d898540544b6db54c8370389d5dca7e3c5#diff-7a84d671f2ddfd02515bba26ecf77d11d5576ad4f6998dd0db2c6b3ba0e323ab

I guess an elegant solution for the adapter would be to allow to provide files via `sendTo` method of scripts.

**Comment by bropat** [comment]
Not at the moment.
