### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Chrille1507** [bropat/ioBroker.eusec#299]
### Adapter version

0.9.7

### JS-Controller version

4.0.23

### Node version

16.18.1

### Operating System type

Linux

### Operating system version

Ubuntu 20.04.5 LTS

### Describe the bug

Der Adapter verbindet sich nicht und es gibt folgende Fehlermeldung:

`Response data is missing [{"code":0,"msg":"Succeed."}]`

### To reproduce

1. Go to 'Instanzen'
2. Click on 'Neu starten des Adapters'

**Comment by bropat** [comment]
Behoben in Version `0.9.8`.
