### ISSUE TITLE
[Bug]: Anmelden funktioniert nicht mehr -  | error | Response data is missing [{"code":0,"msg":"Succeed."}]

### ISSUE THREAD

**Issue by Stormbringer11** [bropat/ioBroker.eusec#300]
### Adapter version

0.9.7

### JS-Controller version

4.0.23

### Node version

16.18.1

### Operating System type

Linux

### Operating system version

Ubuntu 22

### Describe the bug

Hallo Bropat,

ich benutze deinen einzigartigen Adapter eigentlich schon seit dem ersten Tag. In letzter Zeit hatte ich vermehrt Probleme mit der Bilderanzeige in VIS. Daraufhin habe ich versucht den Adapter neu zu installieren. Seitdem bekomme ich leider keine Verbindung mehr zur Eufy Cloud zu Stande und der Adapter bleibt Orange. Es kommt auch keine Einladungs-eMail, wie früher.  Habe zwar einen ähnlichen Fehler bereits gefunden bei meiner Suche aber das betraf HASS. Stehe jetzt ein bisschen auf der Leitung :o)

### To reproduce

.

### Screenshots & Logfiles

`

eusec.0 | 2022-11-26 10:57:14.990 | error | Response data is missing [{"code":0,"msg":"Succeed."}]
-- | -- | -- | --
eusec.0 | 2022-11-26 10:57:14.990 | debug | [HTTPApi.request] Response: [{"response":{"code":0,"msg":"Succeed."}}]
eusec.0 | 2022-11-26 10:57:14.822 | debug | [HTTPApi.request] Request: [{"method":"post","endpoint":"v2/passport/login_sec","token":null,"data":{"ab":"DE","client_secret_info":{"public_key":"x"},"enc":0,"email":"x.x@me.com","password":"x","time_zone":3600000,"transaction":"1669456634822"}}]
eusec.0 | 2022-11-26 10:57:14.821 | debug | [HTTPApi.login] Login and get an access token [{"token":null,"tokenExpiration":null}]
eusec.0 | 2022-11-26 10:57:14.812 | debug | [EufySecurity._initializeInternals] Load previous login_hash: ["08a8076b8f6ebe983584fd52aee6eb01"]
eusec.0 | 2022-11-26 10:57:14.811 | debug | Loaded API_BASE: https://security-app-eu.eufylife.com
host.io-frost-prox | 2022-11-26 10:57:14.428 | info | instance system.adapter.web.0 started with pid 78858
eusec.0 | 2022-11-26 10:57:14.190 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:14.146 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:14.101 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:14.047 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:14.001 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:13.948 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:13.786 | debug | Search can't be optimized because wildcard not at the end, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
eusec.0 | 2022-11-26 10:57:13.753 | info | starting. Version 0.9.7 in /opt/iobroker/node_modules/iobroker.eusec, node: v16.18.1, js-controller: 4.0.23
eusec.0 | 2022-11-26 10:57:13.661 | debug | States connected to redis: 127.0.0.1:6379
eusec.0 | 2022-11-26 10:57:13.658 | debug | States create User PubSub Client
eusec.0 | 2022-11-26 10:57:13.657 | debug | States create System PubSub Client
eusec.0 | 2022-11-26 10:57:13.655 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
eusec.0 | 2022-11-26 10:57:13.604 | debug | Objects connected to redis: 127.0.0.1:9001
eusec.0 | 2022-11-26 10:57:13.602 | debug | Objects client initialize lua scripts
eusec.0 | 2022-11-26 10:57:13.476 | debug | Objects create User PubSub Client
eusec.0 | 2022-11-26 10:57:13.475 | debug | Objects create System PubSub Client
eusec.0 | 2022-11-26 10:57:13.475 | debug | Objects client ready ... initialize now
eusec.0 | 2022-11-26 10:57:13.427 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

`

**Comment by bropat** [comment]
@Stormbringer11

Wird in der nächsten Version behoben.

Du kannst als möglichen Workaround versuchen in der Datei `/opt/iobroker/node_modules/iobroker.eusec/build/main.js` die Zeile 227 wie folgt auszukommentieren (Adapter muss gestoppt sein!):

```javascript
    //trustedDeviceName: "IOBROKER",
```

**Comment by bropat** [comment]
Eufy hat leider angefangen gewisse Werte abzufangen :(

**Comment by tofrie** [comment]
Ich habe das gleiche Problem. Plötzlich ist der Adapter ohne mein Zutun auf gelb…

**Comment by Stormbringer11** [comment]
Danke für die schnelle Antwort bropat, versuche ich dann mal und melde mich wieder. Wenn Eufy jetzt Werte abfangt und dein Adapter nicht mehr geht, ist das wohl ein leichtes Eigentor von Ihnen. Dann können sie ihre Cams die ich beim Black Friday gekauft habe gleich wieder behalten ;D Anstatt, dass sie froh sind, dass sie sich von der Masse rausheben mit dem Adapter.

**Comment by Stormbringer11** [comment]
Du bist der Beste, lad dich auf einen Kaffee ein ;o) Nach Auskommentieren gehts wieder... Hoffe der Pic Fehler ist jetzt durch Zufall auch weg... Ansonsten müsste ich dich mit einem neuen Issue nerven :o)

**Comment by bropat** [comment]
Behoben in Version `0.9.8`.
