### ISSUE TITLE
[Bug]: Thumbnails Downloadgröße nur 27B

### ISSUE THREAD

**Issue by Stormbringer11** [bropat/ioBroker.eusec#301]
### Adapter version

-

### JS-Controller version

-

### Node version

-

### Operating System type

Linux

### Operating system version

Ubuntu 22

### Describe the bug

Wie angedroht :o) Thumbnail download von Doorbells funktioniert nicht mehr. Fehler im Log kommen keine aber wenn man dann auf die Festplatte schaut hat die Datei nur eine Größe von 27B. Komischerweise funktioniert das Ganze bei den Cams schon noch?! Entweder liegt es an den Doorbells oder daran, dass die über die 2. Homebase laufen.

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

.

### Additional context

.

**Comment by Stormbringer11** [comment]
Hilft das weiter? Teste jetzt gerade mit der neuen Dual Cam, weil die installierte 2K zu weit weg ist. momentan wirkt es aber so, wie wenn sie nicht mal Bewegung übermittelt. In der Eufy App taucht es aber auf.

eusec.0 | 2022-11-27 11:09:46.625 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.person_name changed: (ack = true) was already acknowledged, ignore it...
-- | -- | -- | --
eusec.0 | 2022-11-27 11:09:46.570 | debug | [euSec.onStateChange] state eusec.0.xxcameras.xx.person_detected changed: false (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.691 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.person_name changed: Unknown (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.631 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.picture_url changed: https://security-app-eu.eufylife.com/v1/s/g/4xmexMPzKxQ (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.631 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.person_detected changed: true (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.622 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.last_event_pic_html changed: <img src="data:image/jpg;base64,eyJjb2RxlIjowLCJtc2ciOiJTxdWNjZWVkLiJ9" style="width: auto ;height: 100%;" /> (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.622 | debug | [euSec.onStateChange] state eusec.0.x.cameras.x.last_event_pic_url changed: /eusec.0/x/last_event/x.jpeg (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:31.477 | debug | [EufySecurity.onPushMessage] Received push message [{"name":"Doorbell","event_time":1669543770565,"type":91,"station_sn":"x","device_sn":"x","title":"Eufy Security","content":"Doorbell:hunman has been spotted ","push_time":1669543771410,"channel":1,"cipher":147,"event_session":"20221127_110930","event_type":3102,"file_path":"/media/mmcblk0p1/Camera01/h265_20221127110919.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/4mexxMPzKxQ","push_count":1,"notification_style":3}]
eusec.0 | 2022-11-27 11:09:31.477 | debug | [PushNotificationService.onMessage] Normalized push message received [{"name":"Doorbell","event_time":1669543770565,"type":91,"station_sn":"x","device_sn":"xx","title":"Eufy Security","content":"Doorbell:hunman has been spotted ","push_time":1669543771410,"channel":1,"cipher":147,"event_session":"20221127_110930","event_type":3102,"file_path":"/media/mmcblk0p1/Camera01/h265_20221127110919.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/4mexMPzKQ","push_count":1,"notification_style":3}]
eusec.0 | 2022-11-27 11:09:31.477 | debug | [PushNotificationService.onMessage] Raw push message received [{"id":"BF55EC36","from":"348804314802","to":"dUsK_9mbPFfdjCU581TAi-","category":"com.oceanwing.battery.cam","persistentId":"0:1669543771425221%0d2a775cf9fd7ecd","ttl":3600,"sent":"1669543771419","payload":{"device_sn":"xx","payload":{"event_type":3102,"device_sn":"xx","name":"Doorbell","channel":1,"cipher":147,"session_id":"20221127_110930","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/4xmexMxPzKQ","create_time":1669543770565,"file_path":"h265_20221127110919","notification_style":3,"push_count":1,"faceid":0},"station_sn":"T8010P2322161489","google.c.sender.id":"348804314802","title":"Eufy Security","type":"91","push_time":"1669543771410","event_time":"1669543770565","content":"Doorbell:hunman has been spotted "}}]
eusec.0 | 2022-11-27 11:09:31.477 | debug | [PushClient.handleParsedMessage] DataMessageStanza [{"tag":8,"object":{"id":"BF55EC36","from":"348804314802","to":"dUsK_9mbPFfdjCU581TAi-","category":"com.oceanwing.battery.cam","appData":[{"key":"device_sn","value":"T8213P21223805CA"},{"key":"payload","value":"eyJldmVudF90eXBlIjozMTAyLCJkZXZxpY2Vfc24iOiJUODIxM1AyMTIyMzgwNUNBIiwibmFtZSI6IkRvb3JiZWxsIiwiY2hhbm5lbCI6MSwiY2lwaGVyIjoxNDcsInNlc3Npb25xfaWQiOiIyMDIyMTEyN18xMTA5MzAiLCJwaWNfdXJsIjoiaHR0cHM6Ly9zZWN1cml0eSx1hcHAtZXUuZXVmeWxpZmUuY29tL3YxL3MvZy80bWV4TVB6S1EiLCJjcmVhdGVfdGltZSI6MTY2OTU0Mzc3MDU2NSwiZmlsZV9wYXRoIjoiaDI2NV8yMDIyMTEyNzExMDkxOSIsIm5vdGlmaWNhdGlvbl9zdHlsZSI6MywicHVzaF9jb3VudCI6MSwiZmFjZWlkIjowfQ=="},{"key":"station_sn","value":"T8010P2322161489"},{"key":"google.c.sender.id","value":"348804314802"},{"key":"title","value":"Eufy Security"},{"key":"type","value":"91"},{"key":"push_time","value":"1669543771410"},{"key":"event_time","value":"1669543770565"},{"key":"content","value":"Doorbell:hunman has been spotted "}],"persistentId":"0:1669543771425221%0d2a775cf9fd7ecd","ttl":3600,"sent":"1669543771419"}}]
eusec.0 | 2022-11-27 11:09:21.454 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.last_event_pic_html changed: <img src="data:image/jpg;base64,eyJjb2RlIjowLCxJtc2ciOiJTdWxNjZWVkLiJ9" style="width: auto ;height: 100%;" /> (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:21.409 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.last_event_pic_url changed: /eusec.0/xx/last_event/xx.jpeg (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:21.339 | debug | [euSec.onStateChange] state eusec.0.xx.cameras.xx.picture_url changed: https://security-app-eu.eufylife.com/v1/s/g/3BxuYalq6xa (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-11-27 11:09:21.286 | debug | [BatteryDoorbellCamera.processPushNotification] Unhandled doorbell push event [{"name":"Doorbell","event_time":1669543760394,"type":91,"station_sn":"xx","device_sn":"xx","title":"Eufy Security","content":"Doorbell:Something triggered your device","push_time":1669543761206,"channel":1,"cipher":147,"event_session":"20221127_110920","event_type":3308,"file_path":"/media/mmcblk0p1/Camera01/h265_20221127110919.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/3BxfuYalxq6a","push_count":1,"notification_style":3}]
eusec.0 | 2022-11-27 11:09:21.286 | debug | [EufySecurity.onPushMessage] Received push message [{"name":"Doorbell","event_time":1669543760394,"type":91,"station_sn":"xx","device_sn":"xx","title":"Eufy Security","content":"Doorbell:Something triggered your device","push_time":1669543761206,"channel":1,"cipher":147,"event_session":"20221127_110920","event_type":3308,"file_path":"/media/mmcblk0p1/Camera01/h265_20221127110919.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/3BfguYvalqd6a","push_count":1,"notification_style":3}]
eusec.0 | 2022-11-27 11:09:21.286 | debug | [PushNotificationService.onMessage] Normalized push message received [{"name":"Doorbell","event_time":1669543760394,"type":91,"station_sn":"T8010P2322161489","device_sn":"T8213P21223805CA","title":"Eufy Security","content":"Doorbell:Something triggered your device","push_time":1669543761206,"channel":1,"cipher":147,"event_session":"20221127_110920","event_type":3308,"file_path":"/media/mmcblk0p1/Camera01/h265_20221127110919.dat","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/3BuYafglq6xa","push_count":1,"notification_style":3}]
eusec.0 | 2022-11-27 11:09:21.285 | debug | [PushNotificationService.onMessage] Raw push message received [{"id":"BF558AFE","from":"348804314802","to":"dUsK_9mbPFfdjCU581TAi-","category":"com.oceanwing.battery.cam","persistentId":"0:1669543761229786%0d2a775cf9fd7ecd","ttl":3600,"sent":"1669543761222","payload":{"device_sn":"xx","payload":{"event_type":3308,"device_sn":"xx","name":"Doorbell","channel":1,"cipher":147,"session_id":"20221127_110920","pic_url":"https://security-app-eu.eufylife.com/v1/s/g/3BuvYaldxq6a","create_time":1669543760394,"file_path":"h265_20221127110919","notification_style":3,"push_count":1,"faceid":0},"station_sn":"xx","google.c.sender.id":"348804314802","type":"91","title":"Eufy Security","push_time":"1669543761206","content":"Doorbell:Something triggered your device","event_time":"1669543760394"}}]
eusec.0 | 2022-11-27 11:09:21.285 | debug | [PushClient.handleParsedMessage] DataMessageStanza [{"tag":8,"object":{"id":"BF558AFE","from":"348804314802","to":"dUsK_9mbPFfdjCU581TAi-","category":"com.oceanwing.battery.cam","appData":[{"key":"device_sn","value":"T8213P21223805CA"},{"key":"payload","value":"eyJldmVudF90eXBlIjozMzA4LCJkZXZpY2Vfc24iOiJUODIxM1AyMTIyMzgwNUNBIiwibmFtZSI6IkRvb3JiZWxsIiwiY2hhbm5lbCI6MSwiY2lwaGVyIjoxNDcsInNlc3Npb25faWQiOiIyMDIyMTEyN18xMTA5MjAiLCJwaWNfdXJsIjoiaHR0cHM6Ly9zZWN1cml0eS1hcHAtZXUuZXVmeWxxpZmUuY29tL3YxL3MvZy8zQnVxZYWxxNmEiLCJjcmVhdGVfdGltZSI6MTY2OTU0Mzc2MDM5NCwiZmlsZV9wYXRoIjoiaDI2NV8yMDIyMTEyNzExMDkxOSIsIm5vdGlmaWNhdGlvbl9zdHlsZSI6MywicHVzaF9jb3VudCI6MSwiZmFjZWlkIjowfQ=="},{"key":"station_sn","value":"T8010P2322161489"},{"key":"google.c.sender.id","value":"348804314802"},{"key":"type","value":"91"},{"key":"title","value":"Eufy Security"},{"key":"push_time","value":"1669543761206"},{"key":"content","value":"Doorbell:Something triggered your device"},{"key":"event_time","value":"1669543760394"}],"persistentId":"0:1669543761229786%0d2a775cf9fd7ecd","ttl":3600,"sent":"1669543761222"}}]

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
