### ISSUE TITLE
[Bug]: Disconnected  Connected

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#307]
### Adapter version

v0.9.8

### JS-Controller version

4.0.23

### Node version

v16.18.1

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Hallo bropat,
gestern Abend machte Eufy ein Update der App, Version 4.5.1_1109. Seitdem läuft der eusec Adapter über mit den unten ausgeführten Logs.
Fehler macht er keine, aber er füllt die Logs mit Disconnected  Connected was er vorher nicht getan hat, sprich bevor das Update von Eufy ausgerollt wurde. Bei mir läuft er nur über interne Verbidungen zu den Station. Vieleicht weißt du was los ist. Ich weiß noch nicht mal ob es ein Bug ist.
Grüße
Fabio

hello bropat,
last night Eufy updated the app Version 4.5.1_1109. Since then the eusec adapter has been overflowing with the logs listed below.
He doesn't make any mistakes, but he fills the logs with Disconnected Connected, which he didn't do before, i.e. before the Eufy update was rolled out. For me it only runs via local connections to the stations. Maybe you know what's going on. I don't even know if it's a bug.
Regards
Fabio

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

eusec.0 | 2022-12-06 06:46:36.487 | debug | [P2PClientProtocol.handleMsg] Station T8010P2319390051 - received unknown message [{"remoteAddress":"xxxxxxxxxxx","remotePort":32100,"response":{"message":"f169008408000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000","length":136}}]
-- | -- | -- | --
eusec.0 | 2022-12-06 06:46:36.182 | debug | [euSec.onStateChange] state eusec.0.T8010P2319390051.station.connection changed: true (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-12-06 06:46:36.178 | debug | [P2PClientProtocol.handleMsg] Station T8010P2319390051 - received unknown message [{"remoteAddress":"xxxxxxxxxxx","remotePort":32100,"response":{"message":"f1690084080000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a3400000000000000000002102765f2fa0d0000000000000000000210274bf23a340000000000000000","length":136}}]
eusec.0 | 2022-12-06 06:46:36.166 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 17363
eusec.0 | 2022-12-06 06:46:36.166 | debug | [P2PClientProtocol.handleMsg] Station T8010P2319390051 - CAM_ID - Connected to station T8010P2319390051 on host 192.168.2.157 port 17363
eusec.0 | 2022-12-06 06:46:36.163 | debug | [P2PClientProtocol._connect] Station T8010P2319390051 - CHECK_CAM - Connecting to host 192.168.2.157 on port 17363...
eusec.0 | 2022-12-06 06:46:36.162 | debug | [P2PClientProtocol.handleMsg] Station T8010P2319390051 - LOCAL_LOOKUP_RESP - Got response [{"ip":"192.168.2.157","port":17363}]
eusec.0 | 2022-12-06 06:46:36.157 | debug | [P2PClientProtocol.localLookup] Trying to local lookup address for station T8010P2319390051 with host 192.168.2.157
eusec.0 | 2022-12-06 06:46:36.156 | debug | [Station.connect] Connecting to station T8010P2319390051... [{"p2pConnectionType":"ONLY_LOCAL"}]
eusec.0 | 2022-12-06 06:46:31.318 | debug | [euSec.onStateChange] state eusec.0.T8010P2319390051.station.connection changed: false (ack = true) was already acknowledged, ignore it...
eusec.0 | 2022-12-06 06:46:31.155 | debug | [Station.scheduleReconnect] Schedule reconnect to station T8010P2319390051... [{"delay":5000}]
eusec.0 | 2022-12-06 06:46:31.155 | info | Disconnected from station T8010P2319390051

</body>
</html>

eusec.0 | 2022-12-06 06:17:25.758 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 14974
-- | -- | -- | --
eusec.0 | 2022-12-06 06:17:25.293 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 10052
eusec.0 | 2022-12-06 06:17:20.748 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:17:20.281 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:15:30.838 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 20692
eusec.0 | 2022-12-06 06:15:30.552 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 20692
eusec.0 | 2022-12-06 06:15:25.830 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:15:25.540 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:14:22.202 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 29338
eusec.0 | 2022-12-06 06:14:21.985 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 25570
eusec.0 | 2022-12-06 06:14:17.194 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:14:16.976 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:13:12.968 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 18793
eusec.0 | 2022-12-06 06:13:07.958 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:12:33.007 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 10019
eusec.0 | 2022-12-06 06:12:27.996 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:12:04.405 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 23840
eusec.0 | 2022-12-06 06:11:59.398 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:11:24.491 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 10255
eusec.0 | 2022-12-06 06:11:19.479 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:10:55.836 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 18996
eusec.0 | 2022-12-06 06:10:50.826 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:10:15.971 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 14152
eusec.0 | 2022-12-06 06:10:10.959 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:09:47.265 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 22833
eusec.0 | 2022-12-06 06:09:42.253 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:09:07.441 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 29873
eusec.0 | 2022-12-06 06:09:02.435 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:08:38.693 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 14811
eusec.0 | 2022-12-06 06:08:33.681 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:07:58.914 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 24037
eusec.0 | 2022-12-06 06:07:53.902 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:07:30.116 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 11398
eusec.0 | 2022-12-06 06:07:25.109 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:06:50.354 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 11220
eusec.0 | 2022-12-06 06:06:45.242 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:06:21.572 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 23439
eusec.0 | 2022-12-06 06:06:16.562 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:05:41.714 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 16056
eusec.0 | 2022-12-06 06:05:36.701 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:05:13.009 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 16829
eusec.0 | 2022-12-06 06:05:07.997 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:04:33.135 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 12810
eusec.0 | 2022-12-06 06:04:28.126 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:04:04.447 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 11759
eusec.0 | 2022-12-06 06:03:59.436 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:03:24.617 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 15711
eusec.0 | 2022-12-06 06:03:19.605 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:02:55.848 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 24677
eusec.0 | 2022-12-06 06:02:50.836 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:02:16.066 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 10437
eusec.0 | 2022-12-06 06:02:11.053 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:01:47.247 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 17199
eusec.0 | 2022-12-06 06:01:42.235 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 06:01:07.497 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 12927
eusec.0 | 2022-12-06 06:01:02.484 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 06:00:38.679 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 22454
eusec.0 | 2022-12-06 06:00:33.667 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 05:59:58.924 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 17505
eusec.0 | 2022-12-06 05:59:53.912 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 05:59:30.078 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 24443
eusec.0 | 2022-12-06 05:59:25.067 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 05:58:50.412 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 16289
eusec.0 | 2022-12-06 05:58:45.400 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 05:58:21.486 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 14079
eusec.0 | 2022-12-06 05:58:16.475 | info | Disconnected from station T8010N2319491071
eusec.0 | 2022-12-06 05:57:41.843 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 12496
eusec.0 | 2022-12-06 05:57:36.832 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 05:57:12.870 | info | Connected to station T8010N2319491071 on host 192.168.2.168 and port 23099
eusec.0 | 2022-12-06 05:56:33.159 | info | Connected to station T8010P2319390051 on host 192.168.2.157 and port 12229
eusec.0 | 2022-12-06 05:56:32.853 | info | Timeout connecting to station T8010N2319491071
eusec.0 | 2022-12-06 05:56:32.853 | warn | Station T8010N2319491071 - Tried all hosts, no connection could be established
eusec.0 | 2022-12-06 05:56:28.148 | info | Disconnected from station T8010P2319390051
eusec.0 | 2022-12-06 05:55:47.844 | info | Timeout connecting to station T8010N2319491071

![01](https://user-images.githubusercontent.com/88761140/205826506-33b3e02c-14de-46d4-a67f-c4be9a13cbe1.jpg)

**Comment by cratoo** [comment]
Kann ich bestätigen, habe ich hier mit meiner Battery Doorbell auch. Im Debug log hab ich dann noch sowas drin:
```
[P2PClientProtocol.handleMsg] Station T8010P232XXXX - received unknown message 
[{"remoteAddress":"XXXXXXX","remotePort":32100,"response":{"message":
"f169008408000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000000210274bf23a340000000000000000","length":136}}]
```
