### ISSUE TITLE
[Bug]: Access denied für picture_url

### ISSUE THREAD

**Issue by cratoo** [bropat/ioBroker.eusec#308]
### Adapter version

0.9.8

### JS-Controller version

4.0.23

### Node version

14.21.1

### Operating System type

Docker

### Operating system version

Debian 10

### Describe the bug

Scheinbar hat eufy neue Sicherheits-Mechanismen für die picture_url in Nutzung. Sobald die Battery-Doorbell jemand erkennt wird die picture_url aktualisiert mit "https://security-app-eu.eufylife.com/v1/s/XXXX", die Url ist ein Redirect auf z.B. "https://zhixin-security-eu.s3.eu-central-1.amazonaws.com/pushthumb/2022/12/10/station/T8010PXXXX/n5L5sAaZ6ZslPUgx.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXX%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20221210T090017Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXX"

Wenn man die Url mit den ganzen Parametern aufruft bekommt man aber sowohl einen 403, als auch die Meldung:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires>600</X-Amz-Expires><Expires>2022-12-10T09:10:17Z</Expires><ServerTime>2022-12-10T10:06:37Z</ServerTime><RequestId>XXXXX</RequestId><HostId>XXXXXXXtGkits82nOgwz7sDqki1wR3sfIj4nq/S9HMSwcjIRQ=</HostId></Error>
```

Nach einiger Zeit aktualisiert der Adapter die picture_url auf "T8010PXXX~/media/mmcblk0p1/video/20221210110237_c00.jpg".

Gleichzeitig funktioniert der Download der push-Nachricht auch nicht und ich bekomme immer dasselbe HTML:
```
<img src="data:image/jpg;base64,eyJjb2RlIjowLCJtc2ciOiJTdWNjZWVkLiJ9" style="width: auto ;height: 100%;" />
```

### To reproduce

Siehe Beschreibung.

**Comment by youzer-name** [comment]
Since yesterday I am also seeing these errors every ten minutes:

```
EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app.eufylife.com/v1/house/device_list
```

and

```
Stations - Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1671571468216,"socket":1671571468217,"lookup":1671571468219,"connect":1671571468240,"secureConnect":1671571468284,"upload":1671571468284,"response":1671571468299,"end":1671571468299,"phases":{"wait":1,"dns":2,"tcp":21,"tls":44,"request":0,"firstByte":15,"download":0,"total":83}}}]
```

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
