### ISSUE TITLE
[Question]: Update of eufy-security-client?

### ISSUE THREAD

**Issue by youzer-name** [bropat/ioBroker.eusec#310]
### Ask your question

I just started using iobroker and this adapter and have it connected to my Eufy doorbell and Homebase 2, but I am not getting the images and now I have started seeing connection errors in the logs.

I see that the eufy-security-client has been updated to account for changes that Eufy made. Is there something I need to do to update my instance of iobroker.eusec so that it uses the new version of eufy-security-client, or do I just need to wait until the maintainer updates the code for this project?

**Comment by cratoo** [comment]
@youzer-name which updates? The last release/commit of eufy-security-client is version 2.3.0 and the last release of the adapter contains the update to 2.3.0. Also the time (three weeks ago) matches.

**Comment by cratoo** [comment]
As far as I followed @bropat he usually released the client and afterwards also released the adapter. And no I don't know of any easy way to apply the changes on your own. Would also be interested to test it, because I also have the broken images, see #308
