### ISSUE TITLE
[Bug]: Adapter Stopped working tonight

### ISSUE THREAD

**Issue by adultano** [bropat/ioBroker.eusec#311]
### Adapter version

0.9.8

### JS-Controller version

4.0.23

### Node version

16.18.0

### Operating System type

Linux

### Operating system version

10.11

### Describe the bug

As of this morning i cannot start my eu-sec adapter. Log shows:

2022-12-21 06:26:16.956 - error: eusec.0 (31206) EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app-eu.eufylife.com/v1/passport/profile
--
2022-12-21 06:26:16.958 - error: eusec.0 (31206) Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1671600376883,"socket":1671600376884,"lookup":1671600376891,"connect":1671600376903,"secureConnect":1671600376938,"upload":1671600376938,"response":1671600376951,"end":1671600376952,"phases":{"wait":1,"dns":7,"tcp":12,"tls":35,"request":0,"firstByte":13,"download":1,"total":69}}}]

any idea?

thanks and best regards
Marco

### To reproduce

stop adapter and start again - see if it works for you. Maybe something was change at the eufy end

**Comment by Butz86** [comment]
I think it's not a bug of this adapter. 

[https://community.security.eufy.com/t/to-our-eufy-security-customers-and-partners/3568215](url)

> Today, users can still log in to our [eufy.com 1](http://eufy.com/?utm_source=web&utm_medium=web_community&utm_content=3568215&utm_campagin=official&utm_term=) Web portal to view live streams of their cameras. However, users can no longer view live streams (or share active links to these live streams with others) outside of eufy’s secure Web portal. Anyone wishing to view these links must first log in to the [eufy.com 1](http://eufy.com/?utm_source=web&utm_medium=web_community&utm_content=3568215&utm_campagin=official&utm_term=) Web portal.

**Comment by adultano** [comment]
Not sure - but when i restartet the adapter in the past, I received a captcha in the logs browser. But as of today this doenst work anymore. Instead i receive the error as shown before?

**Comment by tofrie** [comment]
Gibt es schon eine Lösung?

**Comment by zbigniewbednarek** [comment]
Hello,
Have the same issue. Nothing has changed on my end it simply stopped working with following errors:



Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1671659320817,"socket":1671659320819,"lookup":1671659320819,"connect":1671659320856,"secureConnect":1671659320957,"upload":1671659320958,"response":1671659320995,"end":1671659320996,"phases":{"wait":2,"dns":0,"tcp":37,"tls":101,"request":1,"firstByte":37,"download":1,"total":179}}}]
--
eusec.0 | 2022-12-21 22:48:41.000 | error | EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app-eu.eufylife.com/v1/passport/profile

I guess that something has changed on eufy side. Im using latest cersion of the adapter

**Comment by Tom-Bruzze** [comment]
Same to me

**Comment by orangelizard** [comment]
Same here.

**Comment by jewink** [comment]
Same here. It stopped working yesterday after 7:00 AM CET.

**Comment by cvoelkel76** [comment]
Same here

**Comment by scottmil** [comment]
Same here too:

￼

**Comment by MatthiasPetersen** [comment]
Same here

**Comment by adultano** [comment]
Der error besteht bei den allermeisten Usern seit 21 dec. es muss ein change auf der eufy Seite sein. Ich hab eine mail an eufy support geschickt und nachgefragt. Möglicherweise hilft es, wenn die anderen user das auch machen um etwas druck aufzusetzen. Schlussendlich habe ich eufy vor allem wegen der api funktion gekauft.

**Comment by cratoo** [comment]
Anyone able to apply an update to the eufy-security-client manually, could checkout the develop-branch of the client, as it seems to contain the fix already (see #310). And no I was not able to do this on my own yet.

**Comment by aklausing** [comment]
Is eufy currently changing things on their api due to the security issues that were detected recently? I have the same issue on the iobroker adapter. I also have a homebridge running with eufy security plugin. The last beta seems to fix the isssue.
