### ISSUE TITLE
[Bug]: last_event_pic_url file is not valid jpeg

### ISSUE THREAD

**Issue by youzer-name** [bropat/ioBroker.eusec#313]
### Adapter version

0.9.9

### JS-Controller version

4.0.2.3

### Node version

16.19.0

### Operating System type

Docker

### Operating system version

Debian GNU/Linux 11 (bullseye)

### Describe the bug

The file stored in /eusec.0/{homebasenumber}/last_event/{doorbellnumber}.jpeg is not a valid image file. The last two have been 27 kb in size and Raspberry Pi desktop throws an error if I try to open in image viewer: 

![image](https://user-images.githubusercontent.com/57046429/209449278-eca44ca9-c463-4f01-af71-36ccec8e5e6f.png)

The date/time of the file did update when a person was detected, but the file is not valid.

When I open the file is text editor, the contents are:
```
{"code":0,"msg":"Succeed."}
```

### To reproduce

1. Run eusec in iobroker
2. Configure eufy connection
3. Wait for person detection
4. Try to open last_event .jpeg file in image viewer
5. Try to open last_Event .jpeg file in text editor

**Comment by TurboEgon** [comment]
Der Inhalt dieser jpgdateien ist auch nur `{"code":0,"msg":"Succeed."}`

**Comment by ElWomSa** [comment]
Downgrade auf vorhergehende Versionen hat bei mir leider auch keinen Erfolg gebracht (Vielleicht wurde seitens Eufy irgendwas umgestellt?!)

**Comment by locito09** [comment]
same here
 i

**Comment by nicomania** [comment]
Bei mir auch

**Comment by bropat** [comment]
The download of notification images has been temporarily removed as decryption of these is not yet supported. It will be added back as soon as it is supported.

Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.
