### ISSUE TITLE
[Question]:  Why is the adapter hogging that much memory?

### ISSUE THREAD

**Issue by seb2010** [bropat/ioBroker.eusec#314]
### Ask your question

Hello. I am using the eusec adapter with only 2 cameras connected. Nevertheless, the adapter is hogging above 300MB of memory compared to the ~50MB of all other adapters. Even the havascript adapter with honestly a LOT of scripts only consumes 250MB.
Is there a particiular reason or even a bug connected to this?

**Comment by Baenker** [comment]
Bei mir hat der Adapter nur 134 MB. Der Admi Adapter hat bei mir 180 und jede der drei JavaInstanzen so zwischen 250 und 300 MB.

Ich habe weitere Adapter die um die 130MB brauchen. Scheint also zumindest bei mir nicht auffällig viel Speicher zu sein.

**Comment by bropat** [comment]
Try latest version `0.9.10`.
