### ISSUE TITLE
[Question]: no device/ house/ station found

### ISSUE THREAD

**Issue by chlaimaach** [bropat/ioBroker.eusec#315]
### Ask your question

Hi
Ich bin durch die Captcha Geschichte durch und habe zunächst keine 2FA aktiviert, um fixer testen zu können, ob es grundsätzlich läuft. Die Instanz ist verbunden und geht komplett auf grün, dennoch wird mir im Log angezeigt, dass keine houses, devices oder stations gefunden wurden. Über den Account sollte aber theoretisch eine Homebase 3 und eine Eufycam 3 verbunden sein.
Habe ich da einfach einen dummen Denkfehler?

Edit_ 
Ok ich wollte das nun einfach nochmal von null an aufrollen. Die Instanz geht nach captcha Eingabe auf grün, dennoch kommen Fehlermeldungen im Log (siehe Anhang)
![Bildschirmfoto 2022-12-30 um 11 17 00](https://user-images.githubusercontent.com/121668608/210059647-a7f095ba-aa28-4936-8dc8-53fe6c71bfed.png)
![Bildschirmfoto 2022-12-30 um 11 22 10](https://user-images.githubusercontent.com/121668608/210060225-4858ab58-bb80-458c-9d83-dbde9aa98497.png)

**Comment by bropat** [comment]
Wurde in der letzten Version behoben (`0.9.10`).
