### ISSUE TITLE
[Bug]: 	Invalid Property personDetected error [{"name":"InvalidPropertyError"}]

### ISSUE THREAD

**Issue by markusk1407** [bropat/ioBroker.eusec#319]
### Adapter version

0.9.9

### JS-Controller version

4.0.24

### Node version

18.13.0

### Operating System type

Linux

### Operating system version

Ubuntu 22.10

### Describe the bug

Hello!
Everytime a person is detected by my Eufy Floodlightcam 2, I get the error: <html><body>
Invalid Property personDetected error [{"name":"InvalidPropertyError"}]

### To reproduce

2. Click on '...'

**Comment by Captain-patty** [comment]
Same here1
