### ISSUE TITLE
[Bug]:	error	Station floodlight manual switch error station: 

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#322]
### Adapter version

0.9.10

### JS-Controller version

 4.0.24

### Node version

18.14.2

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

Hello @bropat I just downloaded the latest and get the following error after starting it.
It is interesting that I have no floodlight but it is an E200 Outdoor Cam. With version 0.9.9 there were no errors. Thank you very much for your effort. The error occurs only when restarting the adapter. Thank you very much for your effort.

**Eufy app version is V4.5.7_1195 otherwise the new version is running without errors.** ;-)

Hallo @bropat habe mir eben mal die latest runtergeladen und bekomme nach dem starten folgenden Fehler.
Interessant ist, das ich gar keine  floodlight habe sondern es eine **E200 Outdoor Cam** ist. Mit der Version 0.9.9 gab es die Fehler nicht. Der Fehler tritt nur beim Neustart des Adapters auf. Vielen Dank für deine Mühen.

**Eufy App Version ist die V4.5.7_1195 ansonten läuft die neue Version bis jetzt fehlerfrei.** ;-)

eusec.0 | 2023-02-24 09:14:22.826 | error | Station floodlight manual switch error (station: T8442P1021210257 channel: 0) [{"name":"DeviceNotFoundError"}]
-- | -- | -- | --
eusec.0 | 2023-02-24 09:14:22.356 | error | Update device T8442P1021210257 properties error [{"name":"DeviceNotFoundError"}]

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

![eusec](https://user-images.githubusercontent.com/88761140/221129702-d9dc7976-4313-4c44-8afc-a7bd2a11648e.jpg)

**Comment by bropat** [comment]
Same problem as described [here](https://github.com/bropat/eufy-security-client/issues/305) incl. explanation of the cause.

**Comment by sansonifabio** [comment]
Okay vielen Dank @bropat für die Info und erklärung, das hatte ich nicht gesehen desahalb schließe ich das hier. ;-)
