### ISSUE TITLE
[Bug]: Error: Station: command CMD_SDINFO_EX failed with error: undefined (146)

### ISSUE THREAD

**Issue by markusk1407** [bropat/ioBroker.eusec#323]
### Adapter version

0.9.10

### JS-Controller version

4.0.24

### Node version

18.13.0

### Operating System type

Linux

### Operating system version

Ubuntu 22.10

### Describe the bug

Every 10min i get the error "Station: xxx command CMD_SDINFO_EX failed with error: undefined (146)"

### To reproduce

2. Click on '...'

**Comment by harryslapalot** [comment]
Same problem here. I don't have any SDs installed, maybe that's the problem.

**Comment by PhilippEngler** [comment]
Could you please provide which station you are using?

**Comment by harryslapalot** [comment]
T8400 Solo Indoor Cam C24

**Comment by PhilippEngler** [comment]
The error is thrown [here](https://github.com/bropat/ioBroker.eusec/blob/9dd377769cb1bfb8ddc2f8670a3835e47667add8/src/main.ts#L1160). I think, @bropat needs to have a look on it (if we need to change anything in the storageinfo-implementation, give me a sign).

**Comment by harryslapalot** [comment]
Any update on this issue? It keeps flooding my log with 2 messages every minute......

**Comment by bropat** [comment]
@PhilippEngler 

There are 2 different commands for getting the SD card / storage data.
I think that not all stations support the command `CMD_SDINFO_EX`. You would have to check if the other command `CMD_SDINFO` should be used here.

@harryslapalot

Which station reports this error? Model?

**Comment by danielschmitz87** [comment]
Hi, since the topic is closed, what is the solution? My log is full of theses error messages!
