### ISSUE TITLE
[Bug]: Guard-Mode T8131 ändert sich nicht mehr.

### ISSUE THREAD

**Issue by Baenker** [bropat/ioBroker.eusec#336]
### Adapter version

0.910

### JS-Controller version

unwichtig

### Node version

unwichtig

### Operating System type

Linux

### Operating system version

unwichtig

### Describe the bug

Modell T8131. Der Datenpunkt Current Guard-Mode wird nicht mehr verändert wenn man den Datenpunkt Guard-Mode ändert. Mit der Vorversion ging das noch. Meine anderen Kameras (Indoor mit Strom funktionieren weiterhin. Auch wenn ich in der Eufy-App den Guard-Mode anpasse wird er nicht übertragen. 

Bei Bedarf kann ich Dir eine Einladung zur Kamera schicken.

Protokoll ist sowohl beim Instanzstart als auch beim ändern vom Datenpunkt still.

### To reproduce

Datenpunkt ändern und anderen Datenpunkt kontrollieren.

**Comment by Baenker** [comment]
Auch mit der aktuellen Version 1.0 keine Änderung. Es ist völlig egal ob ich per Eufy App den Guard-Mode ändere oder über den Adapter es passiert nichts. Das heißt ändere ich in der Eufy App sehe ich keine Änderung in den Objekten. Ändere ich den Guard-Mode über den Adapter ändert sich nichts in der App.
Bei den drei kabelgebundenen Geräten funktioniert das wie es soll. Dort steht im log auch connected to Station. Bei der Batterie Kamera fehlt der Eintrag im log.

Log:



eusec.0 | 2023-05-17 20:43:30.443 | info | Push notification connection successfully established
-- | -- | -- | --
eusec.0 | 2023-05-17 20:43:30.359 | info | Connected to station T8410P312138199C on host 192.168.178.98 and port 28708
eusec.0 | 2023-05-17 20:43:30.355 | info | Connected to station T8410P302125252B on host 192.168.178.83 and port 13828
eusec.0 | 2023-05-17 20:43:30.320 | info | Connected to station T8410P3021252FDD on host 192.168.178.92 and port 14232
eusec.0 | 2023-05-17 20:43:24.198 | info | eusec.0 (11894) go2rtc started: 20:43:24.164 INF go2rtc version 1.5.0 linux/amd6420:43:24.164 INF [api] listen addr=:198420:43:24.165 INF [rtsp] listen addr=:855420:43:24.166 INF [srtp] listen addr=:844320:43:24.172 INF [webrtc] listen addr=:8555
eusec.0 | 2023-05-17 20:43:18.633 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.eusec, node: v16.19.0, js-controller: 4.0.24


@bropat kannst Du Dir das bitte mal angucken? Kann Dir auch einen Zugriff einrichten auf das Gerät.

**Comment by bropat** [comment]
@Baenker 

Höchstwahrscheinlich besteht keine Verbindung über P2P mit der Kamera (T8131).
Die Solo Kameras sind in Vergleich mit Kameras die über einer Station verbunden sind im Nachteil, da sie nur von Zeit zu Zeit "geweckt" werden können und somit keine durchgehende P2P Verbindung aufrecht erhalten werden kann, im Gegenteil zu den anderen wo die P2P Verbindung mit der Station aufrecht erhalten werden kann.
Somit werden die Attribute dieser Solo Kameras alle x Minuten (einstellbar) über Cloud abgefragt (polling). Einige Attribute werden auch durch den Erhalt von Push-Benachrichtigung (falls in der Eufy App aktiviert!) aktualisiert.
Ich Rate somit zu einer Lösung mit Station. ;)

**Comment by bropat** [comment]
@andispammonyer 

Wo steht bitte das die Kamera "S100 WallLight Cam (T84A1)" unterstützt wird? Siehe Dokumentation zu den unterstützten Geräten!

**Comment by Baenker** [comment]
@bropat es lief mit den vorigen Versionen jeden Tag zweimal total zuverlässig. Entweder hat Eufy etwas geändert oder es liegt an Änderungen im Code. Ich würde gerne die Homebase3 nutzen aber Eufy hat bekannt gegeben, dass die Kameras erst ende des Jahres unterstützt werden

**Comment by Baenker** [comment]
Falls ich weitere logs liefern soll sag Bescheid was ich genau liefern soll. Wie geschrieben auch Zugriff zur Kamera wäre möglich

**Comment by Baenker** [comment]
auch mit der 1.1 keine Änderung. Der currend Guard Mode wird einmalig beim starten des Adapters abgefragt und danach nicht mehr verändert.

**Comment by Baenker** [comment]
Es scheint so, dass mit der aktuellen Version man den Modus wieder wechseln kann. Ich schließe den Issue erstmal und beobachte es weiterhin
