### ISSUE TITLE
[Question]: Adapter uses a lot of RAM. Newer version not available in iobroker 

### ISSUE THREAD

**Issue by n0valis** [bropat/ioBroker.eusec#337]
### Ask your question

As stated in issue [314](https://github.com/bropat/ioBroker.eusec/issues/314) the adapter uses a lot of RAM.
You proposed to use the newer version 0.9.10, but in iobroker (repository?) it wouldn't show up. 
Only here https://github.com/bropat/ioBroker.eusec/releases/tag/0.9.10

What's the reason for that? 
And what's the udate procedure?

**Comment by bropat** [comment]
Version 0.9.10 is in beta channel. To install it you must enable the beta repository:

![image](https://github.com/bropat/ioBroker.eusec/assets/2305255/0dcea3b1-d0e6-4a31-9e83-78e6c0a358f5)
