### ISSUE TITLE
[Bug]: last_live wird nicht mehr gespeichert

### ISSUE THREAD

**Issue by hohmannc85** [bropat/ioBroker.eusec#343]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

16.18.1

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Leider wird kein Ordner mehr mit Live bzw dann last_live erstellt. Die Dateien habe ich dann weiter verarbeitet. Ist das mit der neuen Streamfunktion vollständig weg? dann müsste ich meinen Code umstellen. Danke!

### To reproduce

Start Stream -> Stop Stream; keine Datei

**Comment by bropat** [comment]
Es handelt sich nicht um einen Fehler. Diese Funktion wurde entfernt.
