### ISSUE TITLE
[Bug]: undefined Message: undefined (HTTP Code: 404)

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#344]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

18.16.0

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Hello @bropat since 1.0.0 I have these error messages at different times.
I have no idea if this is a bug.
I can't discover any malfunctions of the adapter during operation, everything is running stably and without problems as before.

Greetings
Fabio

---------------------------------------------------------------------------------------------------------------------------------

Hallo @bropat seid der 1.0.0 habe ich diese Fehlermeldungen zu unterschiedlichen Zeiten. 
Keine Ahnung ob das ein Bug ist. 
Ich kann ken Fehlverhalten des Adapters im Betrieb entdecken alles läuft wie bisher stabil und ohne Probleme.

Grüße
Fabio

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

2023-05-20 09:42:42.860 - error: eusec.0 (5907) EufyError - Code: undefined Message: undefined (HTTP Code: 404) - requestUrl: https://security-app-eu.eufylife.com/v1/s/g/IS6FnuCgF

2023-05-20 09:42:42.863 - error: eusec.0 (5907) Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1684568562743,"socket":1684568562743,"lookup":1684568562761,"connect":1684568562779,"secureConnect":1684568562826,"upload":1684568562827,"response":1684568562856,"end":1684568562857,"phases":{"wait":0,"dns":18,"tcp":18,"tls":47,"request":1,"firstByte":29,"download":1,"total":114}}}]

**Comment by Uli977** [comment]
Hallo!
Gleiches Problem bei mir seit Update auf v1.0.0.

Viele Grüße!

**Comment by morskipas** [comment]
Gleiches Problem bei mir auch.

**Comment by SKB-CGN** [comment]
Hallo,
ich habe den Fehler auch, wenn meine Türklingel aktiv wird. Folgender String wird ausgegeben:

`Could not read JSON Data from Server. Following error occured: SyntaxError: Unexpected token < in JSON at position 0`

`Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1687773298249,"socket":1687773298249,"lookup":1687773298277,"connect":1687773298284,"secureConnect":1687773298326,"upload":1687773298326,"response":1687773298342,"end":1687773298345,"phases":{"wait":0,"dns":28,"tcp":7,"tls":42,"request":0,"firstByte":16,"download":3,"total":96}}}]`

**Comment by sansonifabio** [comment]
Hello @bropat

thank you for the new version 1.1.0 
I tested it and the error messages don't appear anymore so I'll close it here.
Best regards
Fabio

------------------------------------------------------------------------------------------------------------------------

Hallo @bropat vielen Dank für die neue Version 1.1.0 habe sie getestet und die Fehlermeldungen treten nicht mehr auf daher werde ich es hier schleißen.
Herzliche Grüße
Fabio
