### ISSUE TITLE
[Bug]: Lange Wartezeit bis zum Streambegin

### ISSUE THREAD

**Issue by hohmannc85** [bropat/ioBroker.eusec#345]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

16.18.1

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Hallo! Wenn der Livestream nun gestartet wird, möchte natürlich gerne gleich das Video auf ein Event aufnahmen. Mit der neuen Videofunktion dauert es jedoch leider 4-6 Sekunden, bis der Stream aktiv ist. Gibt es eine Möglichkeit schneller an das Bildmaterial zu gelangen? Danke!

### To reproduce

Stream Start / Stop

**Comment by cratoo** [comment]
Habe mir die Stream Funktion jetzt auch auf unser Haus Dashboard gebaut und kann bestätigen, dass es ca 8s dauert bis der Stream nutzbar ist (in den 6s nach start_stream bekommt man einen unknown error, in den folgenden 2s zeigt der player ein spinning wheel) und die 8s sind bei mir ziemlich konstant.
Wenn ich mir allerdings das Debug-Log ansehe scheint einfach vorher noch kein valider Stream anzukommen. Insofern tippe ich da nicht auf einen Bug des Adapters. Die Zeit in der App ist ähnlich lange, zumindest hier bei mir mit der Battery Doorbell.

**Comment by hohmannc85** [comment]
Ja, aber mit der alten Methode begann zumindest die Aufnahme direkt, sodass es schön wäre diese Methode zumindest weiterhin zu haben!

**Comment by cratoo** [comment]
Ah ok, bei mir war die alte Methode auch nicht schneller und funktionierte nur im externen vlc player. Aber dann haben wir wohl einfach sehr unterschiedliche use cases :)

**Comment by romeoalfa1975** [comment]
Moin!
Ich bin nun auch auf dieses Phänomen gestoßen und habe ca. 5-10 Sekunden Wartezeit, bis das Livebild erscheint. Mein Dashboard für's Haus ist mit AIO Neo Creator erstellt. Eventuell hat jemand inzwischen etwas besseres herausgefunden?

**Comment by hohmannc85** [comment]
Ich bin auf die alte Version gegangen. Ich hoffe es wird die alte Methode wieder angeboten

**Comment by bropat** [comment]
Die alte Methode wird nicht mehr angeboten. Bitte wechselt zur Version `1.3.0` wo einiges optimiert wurde bezgl. Latenzen beim Streamen (durch go2rtc wird auch WebRTC unterstützt).
