### ISSUE TITLE
[Bug]: Battery Values Incorrect

### ISSUE THREAD

**Issue by n0valis** [bropat/ioBroker.eusec#347]
### Operating system version Debian Bullseye

Values are x% below the values the eufy Security App shows.
x depends, currently 4% lower than the App, but if I restart the adapter values change, are 1% higher than before.
battery_temperature values are off the charts.

In the chart below battery values for 2 eufy2 cams are shown for the past 7 days

![28-05-_2023_17-48-35](https://github.com/bropat/ioBroker.eusec/assets/24315173/bd32e2ff-502f-4889-a4bb-90880384906c)

**Comment by n0valis** [comment]
So appearently the battery values are more or less guesswork.

**Comment by n0valis** [comment]
bropat added the fixed label
Sorry but I think you didn't.
Nothing changed....

**Comment by bropat** [comment]
Should be fixed in latest version.
