### ISSUE TITLE
[Bug]: picture url + person detected

### ISSUE THREAD

**Issue by skatehouse** [bropat/ioBroker.eusec#350]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

16.20.1

### Operating System type

Linux

### Operating system version

Debian 10

### Describe the bug

1. picture URL doesn´t show a picture - if link is sent via telegram e.g

2. Status Person detected isn´t updating

Eufy 2C without cloud

**Comment by freakyfreaky** [comment]
Still an issue with the latest version 1.1.0 an JS Controller 5.0.11

The data point "motion_detected" only works one time on all cameras directly after restarting the adapter. 
Once this has been triggered, no further movements are detected and no new images are stored

**Comment by bropat** [comment]
stale
