### ISSUE TITLE
[Bug]: Push notifications are disabled...

### ISSUE THREAD

**Issue by guitardoc** [bropat/ioBroker.eusec#352]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

18.16.1

### Operating System type

Linux

### Operating system version

Bullseye

### Describe the bug

Seit ein paar Tagen bekomme ich diese Fehlermeldungen:

eusec.0
1813	2023-07-16 20:24:17.404	info	Retry to register/login for push notification

eusec.0
1813	2023-07-16 20:14:17.403	info	Retry to register/login for push notification in 600 seconds...

eusec.0
1813	2023-07-16 20:14:17.401	error	Push notifications are disabled, because the registration failed!

eusec.0
1813	2023-07-16 20:14:17.400	info	Push notification connection closed

eusec.0
1813	2023-07-16 20:14:17.399	error	Create push credentials Error: [{}]

eusec.0
1813	2023-07-16 20:14:17.398	error	registerGcm - Generic Error: [{}]

eusec.0
1813	2023-07-16 20:12:36.065	info	Retry to register/login for push notification

### To reproduce

Tritt permanent auf. Ich habe wissentlich nichts verändert...

**Comment by bropat** [comment]
1. Stop the adapter
2. Try to delete the `persistent.json` file (/opt/iobroker/iobroker-data/eusec.0/persistent.json)
3. Start the adapter (if you have 2fa enabled, you need to run the authentication process again)
4. Verify if the problem persists

**Comment by guitardoc** [comment]
Looks like the problem persists:

`
eusec.0 | 297609 | 2023-07-26 16:30:49.928 | info | Retry to register/login for push notification
-- | -- | -- | -- | --
eusec.0 | 297609 | 2023-07-26 16:30:39.927 | info | Retry to register/login for push notification in 10 seconds...
eusec.0 | 297609 | 2023-07-26 16:30:39.926 | error | Push notifications are disabled, because the registration failed!
eusec.0 | 297609 | 2023-07-26 16:30:39.926 | info | Push notification connection closed
eusec.0 | 297609 | 2023-07-26 16:30:39.925 | error | Create push credentials Error: [{}]
eusec.0 | 297609 | 2023-07-26 16:30:39.924 | error | registerGcm - Generic Error: [{}]
eusec.0 | 297609 | 2023-07-26 16:28:58.593 | info | Retry to register/login for push notification
eusec.0 | 297609 | 2023-07-26 16:28:53.592 | info | Retry to register/login for push notification in 5 seconds...
eusec.0 | 297609 | 2023-07-26 16:28:53.592 | error | Push notifications are disabled, because the registration failed!
eusec.0 | 297609 | 2023-07-26 16:28:53.590 | info | Push notification connection closed
eusec.0 | 297609 | 2023-07-26 16:28:53.589 | error | Create push credentials Error: [{}]
eusec.0 | 297609 | 2023-07-26 16:28:53.588 | error | registerGcm - Generic Error: [{}]
eusec.0 |   | 2023-07-26 16:27:12.330 | info | eusec.0 (297609) go2rtc started: 16:27:11.893 INF go2rtc version 1.5.0 linux/arm6416:27:11.894 INF [api] listen addr=:198416:27:11.898 INF [rtsp] listen addr=:855416:27:11.906 INF [srtp] listen addr=:844316:27:11.915 INF [webrtc] listen addr=:8555
eusec.0 | 297609 | 2023-07-26 16:27:09.446 | info | Connected to station T8010N2320201304 on host 192.168.188.103 and port 27402
eusec.0 | 297609 | 2023-07-26 16:27:09.266 | info | Connected to station T8010P2320100018 on host 192.168.188.100 and port 15607
eusec.0 | 297609 | 2023-07-26 16:26:56.785 | info | 2FA authentication successfully done. Device trusted.
`

**Comment by bropat** [comment]
Please recreate the problem with the new version (`1.1.0`) as it logs more meaningful errors and please share them with me here.

Thank you!

**Comment by guitardoc** [comment]
Seems to work now, thanks for fixing!
