### ISSUE TITLE
[Bug]: Livestream dies with ffmpeg error 

### ISSUE THREAD

**Issue by pijay01** [bropat/ioBroker.eusec#355]
### Adapter version

1.0.0

### JS-Controller version

4.0.24

### Node version

v18.16.1

### Operating System type

Linux

### Operating system version

Ubuntu 22.04.2 LTS

### Describe the bug

Hi,

first of all, thank you for the work on this adapter.

When i try to start the live_stream (set start_stream to true) the camera starts streaming for a short time and I can see the objects rtsp_stream and rtsp_stream_url getting some content. But within 2-3 seconds the camera stops again and the values gets removed.

Attached is the error 

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

eusec.0 | 2023-07-27 20:06:57.679 | error | Station: T8010N23210613B0 Device: T8113N63210616D9 - Error - Stopping livestream... [{}]
-- | -- | -- | --
eusec.0 | 2023-07-27 20:06:57.678 | error | ffmpegStreamToGo2rtc(): ffmpeg stderr: ffmpeg version 5.0.1-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2022 the FFmpeg developers built with gcc 8 (Debian 8.3.0-6) configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg libavutil 57. 17.100 / 57. 17.100 libavcodec 59. 18.100 / 59. 18.100 libavformat 59. 16.100 / 59. 16.100 libavdevice 59. 4.100 / 59. 4.100 libavfilter 8. 24.100 / 8. 24.100 libswscale 6. 4.100 / 6. 4.100 libswresample 4. 3.100 / 4. 3.100 libpostproc 56. 3.100 / 56. 3.100 Input #0, h264, from 'unix:/tmp/eusec.0.1.sock': Duration: N/A, bitrate: N/A Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 1200k tbn Input #1, aac, from 'unix:/tmp/eusec.0.2.sock': Duration: N/A, bitrate: 24 kb/s Stream #1:0: Audio: aac (LC), 16000 Hz, mono, fltp, 24 kb/s Stream mapping: Stream #0:0 -> #0:0 (copy) Stream #1:0 -> #0:1 (aac (native) -> opus (native)) Press [q] to stop, [?] for help
eusec.0 | 2023-07-27 20:06:57.677 | error | ffmpegStreamToGo2rtc(): ffmpeg output:
eusec.0 | 2023-07-27 20:06:57.677 | error | ffmpegStreamToGo2rtc(): An error occurred: ffmpeg was killed with signal SIGSEGV
eusec.0 | 2023-07-27 20:06:57.673 | error | Exception-Code: ECONNRESET: read ECONNRESET
eusec.0 | 2023-07-27 20:06:57.673 | error | Error: read ECONNRESET at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
eusec.0 | 2023-07-27 20:06:57.672 | error | uncaught exception: read ECONNRESET
eusec.0 | 2023-07-27 20:06:57.671 | error | Exception-Code: ECONNRESET: read ECONNRESET
eusec.0 | 2023-07-27 20:06:57.671 | error | Error: read ECONNRESET at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
eusec.0 | 2023-07-27 20:06:57.671 | error | uncaught exception: read ECONNRESET
eusec.0 | 2023-07-27 20:06:52.310 | warn | ffmpegStreamToGo2rtc(): Started

**Comment by freakyfreaky** [comment]
Still an issue with the latest version 1.1.0 an JS Controller 5.0.11

**Comment by bropat** [comment]
I can't do anything about this because this error `ffmpeg was killed with signal SIGSEGV` comes from the "ffmpeg" command itself ([SIGSEV meaning](https://en.wikipedia.org/wiki/Segmentation_fault)), which is supplied as [dependency](https://www.npmjs.com/package/ffmpeg-static). Please open an issue [there](https://github.com/eugeneware/ffmpeg-static/issues).
