### ISSUE TITLE
[Question]: How to start more than on webstream at the same time?

### ISSUE THREAD

**Issue by TbsJah** [bropat/ioBroker.eusec#358]
### Ask your question

Is it possible to start more than one stream at the same time?

At the moment I start each camera individually (7), take a picture and send it by telegram.
This takes a very long time. 
- start stream and wait 9sec (to make sure the stream is reachable)
- create a picture with fmpeg and save 4sec

It would be nice if there were an option or automatic creation of live images.

**Comment by bropat** [comment]
From what I remember, this is a technical limitation on the part of Eufy, at least for the Homebase 2. No idea if this is different for the Homebase 3, as I don't own one myself.
When using a Homebase, the P2P connection is created with the Homebase and not with the individual device. If a Homebase is not used (where supported by the device), it should already be possible to operate several streams simultaneously.

**Comment by TbsJah** [comment]
Thanks for your answer!
Too bad to hear that. But it is as it is :)
In the meantime I have found a faster way
