### ISSUE TITLE
[Bug]: After upgrade to 1.1

### ISSUE THREAD

**Issue by cracyfloyd** [bropat/ioBroker.eusec#361]
### Adapter version

1.1

### JS-Controller version

5.0.11

### Node version

18.17.0

### Operating System type

Docker

### Operating system version

buanet/iobroker:latest-v8

### Describe the bug

in iobroker log i receive follow error:

eusec.0 | 2023-08-09 06:58:07.935 | error | Generic Error [{}]
-- | -- | -- | --
eusec.0 | 2023-08-09 06:58:07.932 | error | JSON parse error [{"data":"\u0006�f�\r�Ht�T�\u0006-�\u00075�a��Y\n�>\u001fb��%~d\|��U+��\u001a!��R\u0005z������533�\u0016I�:f`�\u0013���Z��\u0014\u0002\u0015�a��I�0�ˡA�\u0016o7n�у\u000e\u001f�FS\u000e\u0015ω\u0017M;r�cü�;yvɤ�%��8��W�SA�Q{n��eh�\u0001b\u0018;�aP�F�~\u0010%�\"v\r\u001a���ִ�Y��rya��C�N�8�t��>�𶄶���搫\u0012�`�'!��څ�<�JR\u001c\u0015�\u0010(\u0010��o-ў0\ng�@����tfW��$�s̋ٙ%�5���0�%T��3t1��f��k��7(�YY���","error":{}}]

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
There should be another log line here that tells me which parameter is causing this error.
Unfortunately, it happens that the values received from the cloud are not always JSON compliant.

**Comment by cracyfloyd** [comment]
Seems to be solved with 1.1.1. Thnx

**Comment by TbsJah** [comment]
Can confirm
