### ISSUE TITLE
[Question]: Updating objects in iobroker

### ISSUE THREAD

**Issue by danielschmitz87** [bropat/ioBroker.eusec#364]
### Ask your question

Is it normal that I can't change any object from iobroker Script which then will be updated in the App?

**Comment by bropat** [comment]
Please give me a concrete example so that I understand better what you mean.

**Comment by danielschmitz87** [comment]
Hi, my use case is, that I want to check the status of my Bosch Smart Home Alarm System and based on the condition I want to change the state of the Eufy Security Mode so „Home“, „Away“ etc. but the change I make in iobroker will Not take Affect on the homebase. Is it understandable?

**Comment by bropat** [comment]
Understood.
How do you do this specifically, changing the guard mode?

Post code or a picture or whatever...

**Comment by Baenker** [comment]
Welches Kamera Modell und welche Adapter Version?

**Comment by Catwatch** [comment]
Moin,
- eufyCam 2
- Adapter Version 1.1.0

**Comment by Catwatch** [comment]
Hey,
die heutige, erschienende Version 1.1.1 hat bei mir das Problem behoben.
Tausend Dank dafür!

**Comment by danielschmitz87** [comment]
Kann ich auch von meiner Seite bestätigen. Jetzt funktioniert es.
