### ISSUE TITLE
[Bug]: No verification code / no objects

### ISSUE THREAD

**Issue by Minta79** [bropat/ioBroker.eusec#367]
### Adapter version

1.1.1

### JS-Controller version

4.0.24

### Node version

18.17.1

### Operating System type

Linux

### Operating system version

Proxmox 8.0.4

### Describe the bug

Adapter installed in version 1.1.1, login successful, status: "green". 
But no verification code is sent by email and no objects in object list.

### To reproduce

Adapter installed
Login successful
Adapter green - but no objects
No Email with verification code - no 2fa activated - no emails in SPAM

**Comment by bropat** [comment]
The country setting of the ioBroker installation must match the region of the Eufy app account so that the devices can be found.
