### ISSUE TITLE
S220: Only very few objects available - is this normal?

### ISSUE THREAD

**Issue by Mingarer** [bropat/ioBroker.eusec#369]
### Ask your question

Hi,

I tried to integrate my eufy S220 (battery + solar) with the adapter. Camera is directly connected to the router (no hub in use).
I onl yget a few objects displayed in iobroker.
Any idea if this is correct?
Thanks, Thomas

![S220](https://github.com/bropat/ioBroker.eusec/assets/35626321/371250f6-a248-44e6-8002-d239986b401f)

**Comment by kuckuckmann** [comment]
I got the same. Only less DPs and no real useful information.

**Comment by bropat** [comment]
Yes, because this device is not yet supported.
