### ISSUE TITLE
[Bug]: Adapter & Web-Adapter crashes at startup

### ISSUE THREAD

**Issue by kuckuckmann** [bropat/ioBroker.eusec#370]
### Adapter version

1.1.2

### JS-Controller version

5.0.12

### Node version

18.5.0

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

Adapter is not starting. On Startup Web adapter crashes, then eusec adapter crashes, after that web adapter restarts successfully again. Seee log below.

### To reproduce

Start eusec Adapter

### Screenshots & Logfiles

Log:

<html><body>

web.0 | 2023-09-01 20:26:34.936 | info | http server listening on port 8082
-- | -- | -- | --
web.0 | 2023-09-01 20:26:34.929 | info | Connect extension "eusec/build/lib/web.js"
web.0 | 2023-09-01 20:26:34.912 | info | socket.io server listening on port 8082
web.0 | 2023-09-01 20:26:34.662 | info | starting. Version 6.1.0 in /opt/iobroker/node_modules/iobroker.web, node: v18.5.0, js-controller: 5.0.12
host.ioBroker | 2023-09-01 20:26:32.897 | info | instance system.adapter.web.0 started with pid 36942
host.ioBroker | 2023-09-01 20:26:32.298 | info | Rebuild  for adapter system.adapter.eusec.0 not successful in 3 tries. Adapter  will not be restarted again. Please execute "npm install --production"  in adapter directory manually.
host.ioBroker | 2023-09-01 20:26:32.298 | error | instance system.adapter.eusec.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[1]: Node.js v18.5.0
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]: }
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:   requestPath: 'eufy-security-client'
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:   path: '/opt/iobroker/node_modules/eufy-security-client/package.json',
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:988:32) {
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
host.ioBroker | 2023-09-01 20:26:32.298 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1112:14)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.eusec/build/main.js:22:35)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:102:18)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1012:19)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:787:27)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at Module._findPath (node:internal/modules/cjs/loader:572:18)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:     at tryPackage (node:internal/modules/cjs/loader:359:19)
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught  by controller[0]: Error: Cannot find module  '/opt/iobroker/node_modules/eufy-security-client/build/index.js'. Please  verify that the package.json has a valid "main" entry
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:       ^
host.ioBroker | 2023-09-01 20:26:32.297 | error | Caught by controller[0]:       throw err;
host.ioBroker | 2023-09-01 20:26:32.296 | error | Caught by controller[0]: node:internal/modules/cjs/loader:367
host.ioBroker | 2023-09-01 20:26:31.661 | info | Restart adapter system.adapter.web.0 because enabled
host.ioBroker | 2023-09-01 20:26:31.661 | info | instance system.adapter.web.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
host.ioBroker | 2023-09-01 20:26:31.130 | info | instance system.adapter.eusec.0 started with pid 36935
web.0 | 2023-09-01 20:26:30.972 | warn | Terminated (-100): Without reason

</body>
</html>

**Comment by kuckuckmann** [comment]
Any Info? I need a Feedback or I have to send back the cams

**Comment by bropat** [comment]
This is an installation error and not an adapter issue. Please ask for help in the ioBroker forum.
