### ISSUE TITLE
[Bug]: Cannot change guard mode on floodlight cam anymore

### ISSUE THREAD

**Issue by Captain-patty** [bropat/ioBroker.eusec#373]
### Adapter version

1.1.1

### JS-Controller version

4.0.24

### Node version

18.17.1

### Operating System type

Windows

### Operating system version

10

### Describe the bug

![eusec_error](https://github.com/bropat/ioBroker.eusec/assets/85673809/2a72c191-322f-48c3-a991-f3d55e593197)

I don't exacltly know since when, but I am not able to change the arming state of my two floodlight cams anymore. Homestation is still working, but these two don't.

Tried to uninstall the instance and install it again, but no changes. Plus I get these errors when starting up the instance.

**Comment by Captain-patty** [comment]
I'd love to, but...
![repo](https://github.com/bropat/ioBroker.eusec/assets/85673809/edb31c38-d1d4-4513-ae1a-df3ee5b80431)

**Comment by locito09** [comment]
The new version is 1.1.2
