### ISSUE TITLE
[Bug]: JSON parse error

### ISSUE THREAD

**Issue by AndrewSteel** [bropat/ioBroker.eusec#374]
### Adapter version

1.1.2 and previous

### JS-Controller version

5.0.12

### Node version

18.17.1

### Operating System type

Linux

### Operating system version

6.1.21-v8+ aarch64 GNU/Linux

### Describe the bug

eusec.0 | 2023-09-08 17:04:19.854 | warn | Non-parsable parameter value received from eufy cloud. Will be ignored. [{"type":2707,"value":"{\"r"}]
-- | -- | -- | --
eusec.0 | 2023-09-08 17:04:19.854 | error | JSON parse error [{"error":{"message":"SyntaxError: Unexpected end of JSON input","stacktrace":"SyntaxError: Unexpected end of JSON input\n at JSON.parse (<anonymous>)\n at parseJSON (/opt/iobroker/node_modules/eufy-security-client/build/utils.js:154:21)\n at ParameterHelper.readValue (/opt/iobroker/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n at Camera.updateRawProperty (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:127:57)\n at /opt/iobroker/node_modules/eufy-security-client/build/http/device.js:54:22\n at Array.forEach (<anonymous>)\n at Camera.update (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:53:35)\n at EufySecurity.updateDevice (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n at EufySecurity.handleDevices (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n at HTTPApi.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:167:50)"},"data":"{\"r"}]
eusec.0 | 2023-09-08 17:04:19.853 | warn | Non-parsable parameter value received from eufy cloud. Will be ignored. [{"type":2708,"value":"{\"r"}]
eusec.0 | 2023-09-08 17:04:19.852 | error | JSON parse error [{"error":{"message":"SyntaxError: Unexpected end of JSON input","stacktrace":"SyntaxError: Unexpected end of JSON input\n at JSON.parse (<anonymous>)\n at parseJSON (/opt/iobroker/node_modules/eufy-security-client/build/utils.js:154:21)\n at ParameterHelper.readValue (/opt/iobroker/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n at Camera.updateRawProperty (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:127:57)\n at /opt/iobroker/node_modules/eufy-security-client/build/http/device.js:54:22\n at Array.forEach (<anonymous>)\n at Camera.update (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:53:35)\n at EufySecurity.updateDevice (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n at EufySecurity.handleDevices (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n at HTTPApi.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:167:50)"},"data":"{\"r"}]

WARN and ERROR comes twice with **type:2707** and **type:2708**

### To reproduce

2. Click on '...'

### Additional context

My setup:
* HomeBase 2 (T8010) Firmware: 3.2.9.5h
* eufyCam 2C (T8113) Firmware: 3.0.5.2
* Indoor Cam Pan&Tilt 2K (T8410) Firmware: 2.1.9.5

**Comment by AndrewSteel** [comment]
After
* Indoor Cam Pan&Tilt 2K -- Power of
* eufyCam 2C (T8113) -- Disconnected

the error still occurs.

The incorrect data therefore probably originates from the base station.

**Comment by PhilippEngler** [comment]
This is not an error @bropat can solve. The API from eufy deliver from time to time for some properties wrong values. This is the case here. Your integration should work without limitations.

@bropat: Should we think to made this "error" only visible in debug-loglevel? I think, this has no effect on the user. Also, I have enhanced the `readValue`-funktion to show which device is affected - should I make a PR?

**Comment by AndrewSteel** [comment]
Thank you Philipp for this information. When you say "from time to time" it means to me every minute, which is how the polling interval is set. So if you made this "error" only visible in debug-level, the my log does not overflow permanently ;-)

**Comment by PhilippEngler** [comment]
With from time to time I meant that is dependable per device. The error occur each time, the properties will be retrieved from the API. If you change the corospondending value in the app, the error is gone (but at the moment I did not know what 2708 [DOORBELL_DUAL_RADAR_WD_TIME] stands for at 2C or 2kP&T).

Let's see, what bropat thinks...

**Comment by bropat** [comment]
> @bropat: Should we think to made this "error" only visible in debug-loglevel? I think, this has no effect on the user. Also, I have enhanced the `readValue`-funktion to show which device is affected - should I make a PR?

@PhilippEngler 
Yes, I agree.

**Comment by duylong** [comment]
Same problem with 1.6.4. I downgraded to 1.6.0 and the problem disappeared for me.
Try to see if anyone has the problem.

Home base 2
Cam model : T8142

**Comment by firebowl** [comment]
> Same problem with 1.6.4. I downgraded to 1.6.0 and the problem disappeared for me. Try to see if anyone has the problem.

Actual version is 1.1.2, how do you come to 1.6.0 or 1.6.4?
