### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by SKB-CGN** [bropat/ioBroker.eusec#382]
### Adapter version

1.1.2

### JS-Controller version

5.0.12

### Node version

18.17.1

### Operating System type

Linux

### Operating system version

Debian Bullseye

### Describe the bug

I am constantly getting this error:

`<html><body>

eusec.0 | 2023-10-10 11:31:50.463 | error | JSON  parse error [{"error":{"message":"SyntaxError: Unexpected end of JSON  input","stacktrace":"SyntaxError: Unexpected end of JSON input\n    at  JSON.parse (<anonymous>)\n    at parseJSON  (/opt/iobroker/node_modules/eufy-security-client/build/utils.js:154:21)\n     at ParameterHelper.readValue  (/opt/iobroker/node_modules/eufy-security-client/build/http/parameter.js:50:63)\n     at BatteryDoorbellCamera.updateRawProperty  (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:127:57)\n     at  /opt/iobroker/node_modules/eufy-security-client/build/http/device.js:54:22\n     at Array.forEach (<anonymous>)\n    at  BatteryDoorbellCamera.update  (/opt/iobroker/node_modules/eufy-security-client/build/http/device.js:53:35)\n     at EufySecurity.updateDevice  (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:344:44)\n     at EufySecurity.handleDevices  (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:560:22)\n     at HTTPApi.<anonymous>  (/opt/iobroker/node_modules/eufy-security-client/build/eufysecurity.js:167:50)"},"data":"{\"r"}]
-- | -- | -- | --

</body>
</html>`

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
It is not a bug.
You can find the explanation [here](https://github.com/bropat/ioBroker.eusec/issues/374#issuecomment-1750890391).
Will only be displayed in debug mode in the next version.
