### ISSUE TITLE
Eusec Adapter in Stop / Log files are still written

### ISSUE THREAD

**Issue by sansonifabio** [bropat/ioBroker.eusec#386]
### Adapter version

1.2.1

### JS-Controller version

5.0.12

### Node version

18.18.0

### Operating System type

Linux

### Operating system version

Bookworm Debian

### Describe the bug

Hello @bropat, even if the Eusec adapter is stopped, erros are still written to the log files, for example. Isn't it actually the case that when the adapter is stopped it is also deactivated and no logs are filled?
Greetings
Fabio

Hallo @bropat auch wenn der Eusec Adapter im Stop ist werden weiterhin zum Bespiel Erros in die Logdateien geschrieben. Ist es nicht eigentlich so das wenn der Adapter gestoppt wird er dann auch deaktiviert ist und keine Logs befüllt?
Grüße
Fabio
![Zwischenablage01](https://github.com/bropat/ioBroker.eusec/assets/88761140/c70a4393-9c73-4df0-8f72-bd736747b13d)

![Zwischenablage02](https://github.com/bropat/ioBroker.eusec/assets/88761140/8f0d81bc-1797-492e-a3b2-5cf54f3240de)

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
@sansonifabio 

Can you please send me the screenshot or log extract where I can see the stopping of the adapter and the subsequent error entries?

**Comment by sansonifabio** [comment]
`

2023-11-12 13:17:26.094 - info: host.nuc "system.adapter.eusec.0" disabled
--
2023-11-12 13:17:26.100 - warn: web.0 (19031) Terminated (-100): Without reason
2023-11-12 13:17:26.694 - info: host.nuc instance system.adapter.web.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
2023-11-12 13:17:26.694 - info: host.nuc Restart adapter system.adapter.web.0 because enabled
2023-11-12 13:17:27.742 - info: host.nuc instance system.adapter.web.0 started with pid 19086
2023-11-12 13:17:28.524 - info: web.0 (19086) starting. Version 6.1.10 in /opt/iobroker/node_modules/iobroker.web, node: v18.18.2, js-controller: 5.0.12
2023-11-12 13:17:28.619 - info: web.0 (19086) socket.io server listening on port 8082
2023-11-12 13:17:28.621 - info: web.0 (19086) http server listening on port 8082
2023-11-12 13:18:21.601 - debug: eusec.0 (19046) [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 4... [{"stationSN":"T8442P1021210257","remoteAddress":"192.168.2.33","remotePort":12612,"dataType":"CONTROL","seqNo":4}]
2023-11-12 13:18:21.603 - debug: eusec.0 (19046) [P2PClientProtocol.parseDataMessage] Parsing message - DATA CONTROL - Received data [{"stationSN":"T8442P1021210257","seqNo":4,"header":{"commandId":1103,"bytesToRead":544,"channel":0,"signCode":1,"type":0},"bytesRead":544,"bytesToRead":544,"firstPartMessage":true,"messageSize":560}]
2023-11-12 13:18:21.604 - debug: eusec.0 (19046) [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - Received data [{"stationSN":"T8442P1021210257","commandIdName":"CMD_CAMERA_INFO","commandId":1103,"data":"6d31f3d9b4ac299ce786587a110820ff8c3f738e341b77755442f60ccc5fd63dd180aa65a672080a80138530f47afea4881bcf8f675e6248f2614025393b6d1fa3549b988716cf38ac7ff4a0cd5b41fec4da29fc7826156a2a30a3b88bdf91d5a223b9af790d90af6e4fecf06d5ba93835b72e8232ef33abbbec17c1975817b80a22aef852b513dd7e9b21010bb0dfa453fa3d4d78eaaf5c4b4c9ad8fee09bea4bd30f73e39e227d2b1b9fb602919704122aef20c4e41542b1859d5e2c3f26e4ab6b776200ee1bf1dde41eb6b3b5f66dae84939b33d4374bde6dc4c3380e4a19510015a01aeecb3d426fae41fab274307b17e1d97ff6f9e93e78a01fde1cebc2238aa429d93d238ea58952ec3961715d6800e222f8e09c6671aa035840de711144bd38f836889018421b54756887a3a40c34777245e41a15cf230fdc5f1d3ec3fed84cfbd86e8aa6a672e4afe74d54982012a398ef66185eab8ab471adc603d3ffcd60516db2db4c37c4350a86322ea691687f2d2552604ced7eeec313966c4ab8cef5bdd1f85f9ca44eccfac4bbda2aec66f89fad246e09e64577b660e19139d1c4f67164d38d46a5c7317fb31e1c1a1e36beaae4bc163741340de26c26edea7de5ce927eca0719050409433a2fd8edace88176bdaa6ff13e47867e27530bd5376f5511150e9bcdb216a36375663ca457aba53131708b21d9fbea73e7105b71744b97e3e7988470890e8ce25b460c347175b112146f6a239d0446519abd344c","seqNumber":4,"p2pDataSeqNumber":3,"offsetDataSeqNumber":0}]

`
![Zwischenablage01](https://github.com/bropat/ioBroker.eusec/assets/88761140/14cc531c-1347-41a7-8ca2-c60532577301)

**Comment by bropat** [comment]
Error not reproducible and not traceable from the attached logs

**Comment by sansonifabio** [comment]
Hallo @bropat  obwohl der Adapter in Pause steht füllt er weiter das Log siehe Protokoll:

`<html>
<body>

eusec.0 | 2024-03-03 16:29:40.876 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Received already processed sequence [{"stationSN":"T8030P232242039F","remoteAddress":"192.168.2.22","remotePort":25154,"dataType":"CONTROL","seqNo":59,"expectedSeqNo":60,"queuedDataSize":0}]
-- | -- | -- | --
eusec.0 | 2024-03-03 16:29:40.875 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 59... [{"stationSN":"T8030P232242039F","remoteAddress":"192.168.2.22","remotePort":25154,"dataType":"CONTROL","seqNo":59}]
eusec.0 | 2024-03-03 16:29:40.874 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Received expected sequence [{"stationSN":"T8030P232242039F","remoteAddress":"192.168.2.22","remotePort":25154,"dataType":"CONTROL","seqNo":59,"expectedSeqNo":60,"queuedDataSize":0}]
eusec.0 | 2024-03-03 16:29:40.874 | debug | [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - CMD_NOTIFY_PAYLOAD - Not implemented [{"stationSN":"T8030P232242039F","commandId":60006,"message":"{\"cmd\":60006,\"payload\":{\"nvsipc\":{\"ssid\":\"\",\"routerConnectstatus\":0,\"ipcs\":[]},\"top_status\":0,\"routeripc\":{\"ssid\":\"\",\"routerConnectStatus\":0,\"ipcs\":[]},\"code\":0}}\u0000���\r\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000"}]
eusec.0 | 2024-03-03 16:29:40.873 | debug | [P2PClientProtocol.handleDataControl] Station Handle DATA CONTROL - CMD_NOTIFY_PAYLOAD [{"stationSN":"T8030P232242039F","payload":"{\"cmd\":60006,\"payload\":{\"nvsipc\":{\"ssid\":\"\",\"routerConnectstatus\":0,\"ipcs\":[]},\"top_status\":0,\"routeripc\":{\"ssid\":\"\",\"routerConnectStatus\":0,\"ipcs\":[]},\"code\":0}}\u0000���\r\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000"}]
eusec.0 | 2024-03-03 16:29:40.872 | debug | [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - Received data [{"stationSN":"T8030P232242039F","commandIdName":"CMD_NOTIFY_PAYLOAD","commandId":1351,"data":"8e0f6305814b9920c4ba9c72978f0f96b3279826cc6bfb5d2d5dc012dd4c26bfe0f40a726c13adcc7a340be4ccec3dd95f3499a7cc71f3e2fd98a80edf5915ba49fe988caee05d4e0722232d1d39972965298a84e2f9d2a342207c3094e3b0ee52c6952a8016a797126a9ad3d7b961f0433f7e397459958b8e51b9be10fbc22ca259b53be05529f74c7f89ac6b513c0441e585ec1b544092195a301d999e7f07b08de7bcdc05f63ee177ebdc7f9cf6a8","seqNumber":11,"p2pDataSeqNumber":10,"offsetDataSeqNumber":1}]
eusec.0 | 2024-03-03 16:29:40.871 | debug | [P2PClientProtocol.parseDataMessage] Parsing message - DATA CONTROL - Received data [{"stationSN":"T8030P232242039F","seqNo":59,"header":{"commandId":1351,"bytesToRead":176,"channel":255,"signCode":1,"type":0},"bytesRead":176,"bytesToRead":176,"firstPartMessage":true,"messageSize":192}]
eusec.0 | 2024-03-03 16:29:40.870 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 59... [{"stationSN":"T8030P232242039F","remoteAddress":"192.168.2.22","remotePort":25154,"dataType":"CONTROL","seqNo":59}]
eusec.0 | 2024-03-03 16:26:37.072 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Received already processed sequence [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33,"expectedSeqNo":34,"queuedDataSize":0}]
eusec.0 | 2024-03-03 16:26:37.072 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 33... [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33}]
eusec.0 | 2024-03-03 16:26:37.072 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Received already processed sequence [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33,"expectedSeqNo":34,"queuedDataSize":0}]
eusec.0 | 2024-03-03 16:26:37.071 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 33... [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33}]
eusec.0 | 2024-03-03 16:26:37.071 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Received expected sequence [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33,"expectedSeqNo":34,"queuedDataSize":0}]
eusec.0 | 2024-03-03 16:26:37.071 | debug | [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - CMD_NOTIFY_PAYLOAD - Not implemented [{"stationSN":"T8030P232245105A","commandId":60006,"message":"{\"cmd\":60006,\"payload\":{\"nvsipc\":{\"ssid\":\"\",\"routerConnectstatus\":0,\"ipcs\":[]},\"top_status\":0,\"routeripc\":{\"ssid\":\"\",\"routerConnectStatus\":0,\"ipcs\":[]},\"code\":0}}\u0000���\r\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000"}]
eusec.0 | 2024-03-03 16:26:37.070 | debug | [P2PClientProtocol.handleDataControl] Station Handle DATA CONTROL - CMD_NOTIFY_PAYLOAD [{"stationSN":"T8030P232245105A","payload":"{\"cmd\":60006,\"payload\":{\"nvsipc\":{\"ssid\":\"\",\"routerConnectstatus\":0,\"ipcs\":[]},\"top_status\":0,\"routeripc\":{\"ssid\":\"\",\"routerConnectStatus\":0,\"ipcs\":[]},\"code\":0}}\u0000���\r\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000"}]
eusec.0 | 2024-03-03 16:26:37.070 | debug | [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - Received data [{"stationSN":"T8030P232245105A","commandIdName":"CMD_NOTIFY_PAYLOAD","commandId":1351,"data":"bcc212405575974d15bb97bcebedfb4b9c5c141997fa4be216c4e0869eaa5f45dab7f2063bbfc9d0ed14be9c987436b259c0a0461ee47425b490f71befd7a0c9a6d0f93386783ccb37d7a4d60f959887c7947f79773c14b48bb51b29c7b1422051957e3fe4d0056d57e402783391a0bda819e9931fc5061b35c176545f5be5f0da79356564143d288328e2220cf23bdf172764832dd529c2c02811261fe1bcec3544202273407ab2c8cbf7be6d5b788b","seqNumber":11,"p2pDataSeqNumber":10,"offsetDataSeqNumber":0}]
eusec.0 | 2024-03-03 16:26:37.068 | debug | [P2PClientProtocol.parseDataMessage] Parsing message - DATA CONTROL - Received data [{"stationSN":"T8030P232245105A","seqNo":33,"header":{"commandId":1351,"bytesToRead":176,"channel":255,"signCode":1,"type":0},"bytesRead":176,"bytesToRead":176,"firstPartMessage":true,"messageSize":192}]
eusec.0 | 2024-03-03 16:26:37.067 | debug | [P2PClientProtocol.handleMsg] Received message - DATA CONTROL - Processing sequence 33... [{"stationSN":"T8030P232245105A","remoteAddress":"192.168.2.37","remotePort":12872,"dataType":"CONTROL","seqNo":33}]
web.0 | 2024-03-03 16:26:05.316 | info | http server listening on port 8082
web.0 | 2024-03-03 16:26:05.311 | info | socket.io server listening on port 8082
web.0 | 2024-03-03 16:26:05.227 | info | starting. Version 6.2.3 in /opt/iobroker/node_modules/iobroker.web, node: v18.19.1, js-controller: 5.0.19
host.nuc | 2024-03-03 16:26:04.494 | info | instance system.adapter.web.0 started with pid 14092
host.nuc | 2024-03-03 16:26:03.377 | info | Restart adapter system.adapter.web.0 because enabled
host.nuc | 2024-03-03 16:26:03.377 | info | instance system.adapter.web.0 terminated with code 156 (START_IMMEDIATELY_AFTER_STOP)
web.0 | 2024-03-03 16:26:02.770 | warn | Terminated (-100): Without reason
**host.nuc | 2024-03-03 16:26:02.765 | info | "system.adapter.eusec.0" disabled**


</body>
</html>`
