### ISSUE TITLE
[Feature-request]: E330 Professional Cam

### ISSUE THREAD

**Issue by 3RROR-TINO** [bropat/ioBroker.eusec#391]
### Ask your question

Hi ist hier schon eine Aufnahme in de Adapter  in Arbeit? Kann gern meinen Zugang zu Verfügung stellen! Danke

**Comment by romeoalfa1975** [comment]
Oh, das wäre toll! Bei mir stehen die E330-Kameras alle als unbekanntes Gerät in der Objektliste.

**Comment by bropat** [comment]
Vorerst muss das Gerät im Treiber-Projekt implementiert werden. Siehe dazu [hier](https://github.com/bropat/eufy-security-client/issues/422).

Die zur Zeit unterstützten Gerät findet man [hier](https://bropat.github.io/eufy-security-client/#/supported_devices).

**Comment by lenusch** [comment]
Guten Tag, das ist noch nicht möglich oder?
