### ISSUE TITLE
[Feature request]: SoloCam S340 / T8170

### ISSUE THREAD

**Issue by BuRnColonia** [bropat/ioBroker.eusec#392]
### Describe the solution you'd like

Gibt es schon Arbeiten zur Unterstützung der T8170? Wenn benötigt kann ich gerne Infos über die vorhandene Kamera zur Verfügung stellen. Im ioBroker sind bisher nur rudimentäre Infos vorhanden.

**Comment by DrRingeDing** [comment]
@bropat When will you release version 1.3.0? I would test it from the Develop Branch
