### ISSUE TITLE
Station: T8030Pxxxxxxxxxx command CMD_SDINFO_EX failed with error: undefined (-148)

### ISSUE THREAD

**Issue by GM-Jokemaster** [bropat/ioBroker.eusec#397]
### Ask your question

Hi everyone!

regarding to the implementation/fix : Is it already in the latest Git Version ? 
Could not figure out if it is already in the v1.2.1 ?? (close to the closeing Date of Post https://github.com/bropat/ioBroker.eusec/issues/394 )

If so: I am still getting this errors
If not: Is there any sign when it is in the next version? 
Thank You all for the good Work ! 👍🏼 

My Hardware: S380 with Harddrive, 3x T8160, 1x T8213

**Comment by CommanderXXL** [comment]
I have the same issue. This seems to be due to an update on Eufy side in the API. Will there be a fix soon?

**Comment by GM-Jokemaster** [comment]
It schould in teh "next" version regarding to the already Closed Post -> https://github.com/bropat/ioBroker.eusec/issues/394

**Comment by bropat** [comment]
@GM-Jokemaster 

The fix will be included in version `1.3.0`. Please don't ask for ETA.
