### ISSUE TITLE
EuSec-Instanz leuchtet nur noch rot

### ISSUE THREAD

**Issue by romeoalfa1975** [bropat/ioBroker.eusec#398]
### Ask your question

Hallo,
was kann ich tun, wenn meine Instanz von EuSec rot bleibt? Alle drei Punkte sind rot (Verbunden mit Host, usw.) Ich habe die Instanz gelöscht, den Adapter deinstalliert, ioBroker neu gestartet und den Adapter wieder neu installiert und meine Benutzerdaten eingegeben. Er bleibt jedoch rot.
Gibt es einen einfachen Tipp, was hier passiert sein könnte? An meiner Konfiguration der Eufy Homebase etc. habe ich seit Wochen nichts mehr geändert.
Vielen Dank schon einmal im Voraus :-)

**Comment by bropat** [comment]
Siehe unter `Protokolle` nach ob irgendwelche Fehler ersichtlich sind.
Wenn ja teile sie hier mit, ansonsten bräuchte ich eine Glaskugel um dir antworten zu können ;).

**Comment by romeoalfa1975** [comment]
Moin! 

So, ich habe geschaut, im Protokoll steht gar nichts dazu, aber ich habe jetzt folgendes getan und es funktioniert wieder:

- Eusec-Adapter und Instanz deinstalliert/gelöscht über das iobroker UI
- Über die Konsole die Datei package-lock.json im Editor geöffnet
- dort alle Einträge, die "Eufy" enthalten gelöscht
- Anschließend ließ sich der Eusec-Adapter wieder installieren und leuchtet grün

Ich habe aber letztendlich keine Ahnung, warum das so ist.
