### ISSUE TITLE
Need support for eufy Security SoloCam S340 (T8170)

### ISSUE THREAD

**Issue by padddy79** [bropat/ioBroker.eusec#399]
### Describe the solution you'd like

Hello,

need support for camera S340. In eusec adapter 1.2.1 in iobroker the cam is shown as unknown device. Only basic information are visible.
![image](https://github.com/bropat/ioBroker.eusec/assets/149885276/bff23483-cd80-4cfd-b35e-a331965744f4)
Could you please implement the function of the cam? I'm interest in the control of the 4 fixed camera positions.

Thanks and BR
Patrick

**Comment by PhilippEngler** [comment]
Take a look at #392.
