### ISSUE TITLE
[Bug]: Country US in den Log-Einträgen des Adapters - Land in der app Germany

### ISSUE THREAD

**Issue by Minta79** [bropat/ioBroker.eusec#412]
### Adapter version

1.2.1

### JS-Controller version

5.0.17

### Node version

18.19.0

### Operating System type

Other

### Operating system version

Proxmox 8.0.4

### Describe the bug

Meldung im Log:
Loaded API [{"apieBase":"https://security-app.eufylife.com","country":"US","username":"minta@gmx.de","persistentData":...

Resultat: Keine Geräte, kein Verification Code kommt an 

### To reproduce

Meldung im Log:
Loaded API [{"apieBase":"https://security-app.eufylife.com","country":"US","username":"minta@gmx.de","persistentData":...

Resultat: Keine Geräte, kein Verification Code kommt an

**Comment by bropat** [comment]
Das ist kein Bug. Der Adapter verwendet als "Country" Setting die Land Einstellung von ioBroker. In der nächsten Version wird es im Adapter möglich sein diese Einstellungen zu überschreiben.
