### ISSUE TITLE
[Question]:  not getting any motion or people detected events.

### ISSUE THREAD

**Issue by netTrek** [bropat/ioBroker.eusec#413]
### Ask your question

Hi,

I have three Homebase 2's running and ten 2c's pro camera. The connection to your Adapter works, except for the error that none of the bases return SD information.

According to the logs, the push services are successfully initialised: "Push notification connection successfully established".

Unfortunately, I cannot receive any motion or people events. My phone (eufy app) processes the push messages.

I have tried testing the adapter with a local and a fast connection, but unfortunately the result remains the same.

I don't think it's your fault, as your adapter processes the push messages perfectly. But the question is, do I need to look out for anything in particular? I even removed all devices from HomeKit, but unfortunately with the same result :(

If you or anyone in the community could give me some tips, I would be very grateful!

**Comment by bropat** [comment]
I don't understand your problem, as you write that you receive the push notification in the adapter.
