### ISSUE TITLE
[Question]: When will the new Version be final?

### ISSUE THREAD

**Issue by heckmic** [bropat/ioBroker.eusec#416]
### Ask your question

When will the new Version be final? Is there still development?

**Comment by CptWindows** [comment]
Development in the Develop Branch is making progress
You can already use it therotically, I have installed it myself as a test.

But otherwise he's only doing this in his spare time and so it may take some time until the version is final. I think you just have to be patient.

**Comment by romeoalfa1975** [comment]
Ich würde gerne auch jetzt schon eine Betaversion testen, wo kann ich sie herunterladen?

**Comment by BuRnColonia** [comment]
Is everything OK? There is no reaction on the issues anymore ... Hope the project isn't dying ...

**Comment by GM-Jokemaster** [comment]
Hope so too ... Yes hes developping in his spare Time ... but the promise its X month ago...
