### ISSUE TITLE
[Bug]: 1.3.0 Dev-Version draining battery life of SoloCam S340 / T8170 extremely 

### ISSUE THREAD

**Issue by BuRnColonia** [bropat/ioBroker.eusec#420]
### Adapter version

1.3.0 dev

### JS-Controller version

5.0.19

### Node version

18.16.0

### Operating System type

Linux

### Operating system version

Ubuntu 22.04.3

### Describe the bug

Logfile shows:

eusec.0 (832193) [http] [Station.onConnect] Connected to station T8170XXXXXXXXXXX on host 192.168.XXXXXX and port XXXXX
eusec.0 (832193) [p2p] [Timeout._onTimeout] Initiated closing of connection to station T8170XXXXXXXXXXX for saving battery.

all day with random Ports in a one minute rhythm. 

Most entries with my local IP 192.168... an sometimes with external 52.xxx.xxx.xxx or 35.xxx.xxx.xxx

On Tuesday morning I installed the 1.3.0 dev version and on Friday evening the camera was completely empty - but with good weather and solar panel running. 

Battery history of the last 24 Hours:

<img width="1454" alt="battery-history" src="https://github.com/bropat/ioBroker.eusec/assets/61551680/f0693a90-5b0f-44aa-9f5a-74c5f198315f">

### Logfiles

[10-minute-log-eusec130.txt](https://github.com/bropat/ioBroker.eusec/files/14898276/10-minute-log-eusec130.txt)

**Comment by MirU-cell** [comment]
Same symptoms on my E340
