### ISSUE TITLE
[Question]: E340: No objects for the device available

### ISSUE THREAD

**Issue by MirU-cell** [bropat/ioBroker.eusec#429]
### Adapter version

1.2.1

### JS-Controller version

5.0.19

### Node version

18.20.2

### Operating System type

Linux

### Operating system version

debian 12 (RaspPi)

### Describe the bug

Adapter connects and turns green. It also does find the device (E340) and shows info about firmware etc.  
However there are 0 object points for the video links, alarm trigger or anything else are being created.
![image](https://github.com/user-attachments/assets/f3470fa3-068a-4c0f-bcde-4922d3256b3e)

It is connectiong to the webservice using a separate account.
Also there is a frequent timeout shown in the log: 
once a minute the adapter is reconnecting

### To reproduce

2. Click on '...'

### Additional context

In the beginning the locale for the linux was en_GB while the devices have been created under Germany. following some post here i've change this to de_DE with no effekt.

**Comment by MirU-cell** [comment]
OK. looks like the e340 will only be working with the next release. It is listed as being supported. However when looking in the eufy-security-client release notes: It is only supported from 3.0.0 on. Parte of the eusec 1.2.1 is eufy-security-client 2.9.1 only.

Any way i can update the client only to 3.0.0 (if that would work with eusec 1.2.1?

**Comment by bropat** [comment]
Released new eusec in beta channel
