### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by n0valis** [bropat/ioBroker.eusec#441]
### Adapter version

121

### JS-Controller version

5.0.19

### Node version

18.20.2

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

Although nothing changed I get a login error since maybe 3 weeks ago:
Login - Generic Error: [{"error":{"cause":{"name":"RequestError","code":"ECONNREFUSED"

### To reproduce

nothing special

**Comment by bropat** [comment]
> Login - Generic Error: [{"error":{"cause":{"name":"RequestError","code":"ECONNREFUSED"

This is a network issue on your side.
