### ISSUE TITLE
[Bug]: Some Errors in the log

### ISSUE THREAD

**Issue by markusk1407** [bropat/ioBroker.eusec#446]
### Adapter version

1.3.2

### JS-Controller version

6.0.11

### Node version

20.17.0

### Operating System type

Linux

### Operating system version

Debian 12

### Describe the bug

Station: XXXX command CMD_DATABASE_IMAGE failed with error: ERROR_CONNECT_TIMEOUT (-134)

Station: XXXX command CMD_DATABASE_IMAGE failed with error: ERROR_CONNECT_TIMEOUT (-134)

[p2p] [Timeout._onTimeout] All address lookup tentatives failed. [{"stationSN":"XXXX"}]

[p2p] [Timeout._onTimeout] All address lookup tentatives failed. [{"stationSN":"XXXX"}]

Station: XXXX command CMD_CAMERA_INFO failed with error: ERROR_CONNECT_TIMEOUT (-134)

### To reproduce

*

**Comment by bropat** [comment]
These are connection problems
