### ISSUE TITLE
Images only refresh at Adapter restart and Log error

### ISSUE THREAD

**Issue by andiweli** [bropat/ioBroker.eusec#447]
### Adapter version

1.2.1

### JS-Controller version

6.0.11

### Node version

20.17.0

### Operating System type

Linux

### Operating system version

Bookworm

### Describe the bug

Images of cameras only refresh when adapter is restarted. No automatic refresh even eufy App has new images of last movement in cameras. 

Eufy Cam 2C

Also I have this error every few minutes in the log:

Station: T8010N2322xxxxxx command CMD_SDINFO_EX failed with error: undefined (-148)

### To reproduce

As described above

**Comment by bropat** [comment]
> Station: T8010N2322xxxxxx command CMD_SDINFO_EX failed with error: undefined (-148)

Update to latest version in the beta channel (#379 #440).

> Images of cameras only refresh when adapter is restarted. 

The images are only updated via the push notifications, if these are not activated, they are not updated.
When the adapter is started, they are received once by the cloud, as this caches the last image.

**Comment by andiweli** [comment]
Seems not to solve the issue.
Where to activate "push notifications"? In Eufy App they are activated. I
find no option in your adapter.

Now the new error for web.0:

Cannot start extension "eusec.0": Error: Cannot find module
'iobroker.eusec/build/lib/web.js'Require stack:-
/opt/iobroker/node_modules/iobroker.web/main.js

Am Sa., 28. Sept. 2024 um 13:23 Uhr schrieb bropat ***@***.***

**Comment by bropat** [comment]
> Cannot start extension "eusec.0": Error: Cannot find module
'iobroker.eusec/build/lib/web.js'Require stack:-
/opt/iobroker/node_modules/iobroker.web/main.js

Look [here](https://github.com/bropat/ioBroker.eusec/issues/436#issuecomment-2336734160).

**Comment by andiweli** [comment]
Oh thanks 👍🏻Am 28.09.2024 um 14:27 schrieb bropat ***@***.***>:﻿

Cannot start extension "eusec.0": Error: Cannot find module
'iobroker.eusec/build/lib/web.js'Require stack:-
/opt/iobroker/node_modules/iobroker.web/main.js

Look here.

**Comment by andiweli** [comment]
With deacitvated web Adapter no images are shown.
Is there another way?

Am Sa., 28. Sept. 2024 um 14:27 Uhr schrieb bropat ***@***.***

**Comment by bropat** [comment]
Who told you to deactivate the web adapter?

Read carefully: https://github.com/bropat/ioBroker.eusec/issues/436#issuecomment-2336734160

**Comment by andiweli** [comment]
3 posts up, you...

"Version 1.3.0 no longer requires the web adapter.
This dependency has been removed."

**Comment by bropat** [comment]
> "Version 1.3.0 no longer requires the web adapter.
This dependency has been removed."

That was just a general statement that the eusec adapter no longer requires the web adapter. No indication of an action.

That was the solution:

> The only way I am aware of to remove this error is to uninstall and reinstall the eusec adapter.

**Comment by andiweli** [comment]
Whatever... it works now with the images :)

Battery stats are still frozen and only update when the adapter is restarted.
