### ISSUE TITLE
Feature request: Button zum aktualisieren des Snapshots einer Kamera

### ISSUE THREAD

**Issue by thogens** [bropat/ioBroker.eusec#9]
Hallo!

Im Moment wird beim Aufrufen der URL des Snapshots immer das letzte "Alarmbild" der entsprechenden Eufy gezeigt.
Toll wäre es, wenn man händisch ein aktuelles erstellen könnte. Dann könnte man dieses nämlich weiter verarbeiten und beispielsweise über Telegram versenden...

Grüße,
Thomas

**Comment by bropat** [comment]
Hallo @thogens,

die URL Snapshots (letztes "Alarmbild") wird direkt von der Eufy-API zu Verfügung gestellt. 
Bis jetzt ist mir eine solche Funktionalität in der API nicht aufgefallen. Ich denke dies ist nur mit dem kurzzeitigen aktivieren des Livestreams, das Erstellen eines Snapshots und deaktivieren des Livestreams möglich.

**Comment by TbsJah** [comment]
Just for feedback 
Ein Aktivieren des Livestreams erstellt kein neues Bild
