### ISSUE TITLE
Feature request: Get still image when pressing the doorbell

### ISSUE THREAD

**Issue by skank01** [bropat/ioBroker.eusec#96]
I would like to get  a still image when the eufy doorbell is pressed.
or in further stadium the live video.

But first please give us a still image

The follow integration https://github.com/matijse/eufy-ha-mqtt-bridge/     has an image, but its sometimes blank or too slow to capute the right one.

**Comment by skank01** [comment]
See also https://github.com/matijse/eufy-ha-mqtt-bridge/issues/45
and
https://github.com/matijse/eufy-ha-mqtt-bridge/issues/23

**Comment by bropat** [comment]
@skank01 Try version 0.6.0 and let me know.
